### ISSUE TITLE
固定IPの設定は可能でしょうか

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#1]
運用時に固定IPで使用したいと思っています。可能でしたら対応お願いします。

**Comment by mnakada** [comment]
wpa_supplicantとdhcpcがAtomCamの本来のプログラムであるiCamera_appの中でconfigを生成されて再起動されるので、外から対応するのは難しいです。
また外から設定を変更できたとしてもiOSやAndroidのアプリの設定との整合が取れなくなるのでおすすめできないです。
mDNSで名前でアクセスできるようになっているので、mDNSのhost名でアクセスするようにするか、ルーターのDHCPの設定で固定IPを振ることで対応することはできませんか？

**Comment by kurokouji** [comment]
詳しい、iCamera_app　の情報お知らせいただきありがとうございます。
>mDNSのhost名でアクセスするようにするか、ルーターのDHCPの設定で固定IPを振ることで対応
試してみます、1週間程度連続運用すると音信不通になる場合があるため対策を検討しております。
有用な、コードの公開ありがとうございます。また気になる点質問させていただきます。
