### ISSUE TITLE
インターネットに接続せず、RTSP通信について

### ISSUE THREAD

**Issue by galaxygliese** [mnakada/atomcam_tools#100]
動画のタイムスタンプ時刻はずれても良く、インターネットには接続させずに、RTSP通信を考えております。
これは実現可能なのでしょうか。必ずatomtechのawsサーバーに起動時に接続する必要があるでしょうか。

**Comment by mnakada** [comment]
モニタリングのNetwork確認等をoffにして、AtomCamの検知機能をoffにする（検知機能はawsからダウンロードされる）などできるだけ余計なものを動かさないとできるかもしれません。
やってみてください。

**Comment by Hiii555** [comment]
LAN内だけでAtomCam映像を見たいという事でしたら外行きの検知機能OFFで設定画面が見られるようでしたら
RTSP再生ができるアプリで見たり、NASなどの機能で録画・再配信など出来てます。的外れな回答でしたらすいません。
![internal](https://github.com/mnakada/atomcam_tools/assets/161435860/12b2ee24-5a3d-459a-a2f7-013a89274db7)
![internal1](https://github.com/mnakada/atomcam_tools/assets/161435860/b5552f9c-798c-42d6-ac2f-fe13655f7c5b)
![internal2](https://github.com/mnakada/atomcam_tools/assets/161435860/7f45fe7e-ef51-475b-9dbf-9d618cb424bd)

**Comment by galaxygliese** [comment]
早速のご返信いただきありがとうございます。
SDカードに問題があったらしく、FAT32で再度フォーマットして、検出設定を全てOFFにしたらできました。
別のデバイスでもう一度確認してみようと思います！動作の問題なければクローズさせていただきます。

**Comment by galaxygliese** [comment]
ご回答いただきありがとうございました。
別デバイスでも動作確認できました。
さて、Pythonから読み込みを行ってみると、次の様な課題が見つかりました。

```
>>>cap = cv2.VideoCapture("rtsp://atomcam.local:8080/video0_unicast")
[tcp @ 0x55d36dd237c0] Failed to resolve hostname atomcam.local: Temporary failure in name resolution
```
と表示されフレームが正常に取得されませんでした。

VLCのデスクトップアプリケーションから行うと問題なく動画を取得できていたため、PythonのVLCライブラリから読み込みを行ってみると次の通りでした：

```
>>>player = vlc.MediaPlayer("rtsp://atomcam.local:8080/video0_unicast")
>>>player.play()
[00000001290082f0] main input error: Your input can't be opened
[00000001290082f0] main input error: VLC is unable to open the MRL 'rtsp://atomcam.local:8080/video0_unicast'. Check the log for details.
```

もし、何か原因について思い当たりがありましたら、ご教示いただけますと幸いです。

**Comment by mnakada** [comment]
IPアドレスで指定してもダメですか？

**Comment by galaxygliese** [comment]
ご返信ありがとうございます。
RTSPの場合は、ネットに繋がった場合はIPアドレスで動画取得できました。（確認が必要かもしれないですが、ネットに繋がってない場合は、IPアドレスでもダメでした。）
しかし、RTSPではなく、http://{ip_address}/cgi-bin/get_jpeg.cgi にリクエストすることで、画像を取得できましたため、こちらのイシューをクローズさせていただきます。
ご対応いただきありがとうございました。
