### ISSUE TITLE
連続録画の録画スケジュールが設定できない

### ISSUE THREAD

**Issue by otatm** [mnakada/atomcam_tools#101]
お世話になります。
今回初めてATOM CAM2を使う者です。

表題の通り，「録画スケジュール」がうまく使えず困っています。

１．録画スケジュール：スケジュールで曜日，時間帯のセットはできるのですが，
　　設定どおりに録画がされません。
　　なお，常時録画に設定すればSDカードに記録されます。

２．設定画面を一旦閉じて開きなおすと録画スケジュールの確認ができません。
　　下面の表示（スイッチ）は「スケジュール」になっているのですが，
　　スケジュールの内容（曜日，時間帯）の表示がされません。

環境は,
ATOM CAM2 ファームウェア ver.4.58.0.120
ATOMCAM Hack　ver.2.4.3
設定ブラウザ WIndows10 google chrome ver.124.0.6367.202
です。

操作方法が間違っている（他にも設定しなければいけない所がある，等）のでしょうか。
ご教示いただければ幸いです。

よろしくお願いします。

**Comment by mnakada** [comment]
ご指摘ありがとうございます。
次回のリリースで修正します。

**Comment by otatm** [comment]
回答ありがとうございます。
よろしくお願いします。

**Comment by mnakada** [comment]
Ver.2.5.0で修正しました

**Comment by otatm** [comment]
修正ありがとうございます。
取り急ぎ動作確認結果のご報告です。

スケジュール録画のセットをした後に設定画面を開きなおしても
スケジュールの確認ができる事を確認しました。
さらに，一度常時録画にセットしなおして再度スケジュールにトグルした時に
前のスケジュールを覚えていることも確認しました。（これは便利ですね。）

しかしながら，SDカードに対して，スケジュールに対応して時間のフォルダーは
作られるものの，mp4ファイルは記録されませんでした。
メディア設定でSDカードへの直接記録をON/OFFしてみましたが結果は変わりません。
（常時録画にすれば記録されます）

よろしくお願いします。

**Comment by mnakada** [comment]
すみません。書き込みまで確認できてませんでした。
Ver.2.5.1 で修正しました。

**Comment by otatm** [comment]
早速修正していただきありがとうございます。
おかげ様でスケジュール録画されるようになりましたが，
録画をスキップしてしまう現象がみられました。
以下，ご報告です。

検証時間　日曜　0:15 ～　10：15

【設定１】月～日（全日） 0:25～0:27
　　録画（mp4）　0:24～0：27　ファイル数 3　　

【設定２】日曜　　　　　 0:30～0:33
　　録画（mp4）　0:29～0：33　ファイル数 4　　

【設定３】月～日（全日） 1:05～1:08
　　録画（mp4）　なし　　　＝　設定どおりに録画されず

【設定４】月曜　　　　　 1:15～1:20
　　録画（mp4）　なし

【設定５】月～日（全日） 3:15～3:20
　　録画（mp4）　3:14～3：20　ファイル数 6

・設定３のスケジュールが実行されませんでした。
　検証時間が短いので，どのようなパターンだとでスキップしてしまうのか
　まではわかりません。
・録画されたスケジュールについては，
　録画開始時間が設定よりも1分早くなっていました。
　（あまり支障はないと思いますが…。）　　
・録画がスケジュールされていない時間帯についても
　毎時フォルダーだけ生成されます。
　今回の場合，01，02，04，05，06，07，08，09，10 時の
　フォルダーが空でした。（01時は設定３のmp4ファイルがあるはずですが空です。）　
　勝手で恐縮ですが，できれば空のフォルダーは作られない方が便利だと思います。

よろしくお願いします。

**Comment by mnakada** [comment]
録画がスキップする現象はAtomCamの仕様です。
常時録画にしていても何も検知されない状態だと録画がスキップされます。
コードを見たところ、画像と音声をチェックしているようです。
画像の変化がなく、音がない状態だと記録がスキップされます。

不要なフォルダが作成されるのもFWが勝手に作成しているため、作成自体は止められません。
３日後くらいに空のフォルダは削除するようにしています。

録画時間のずれは生成されたmp4ファイルの後処理のタイミングで時刻を確認して処理しているので、必要な時間範囲に少し余裕を持たせて設定してください。

**Comment by otatm** [comment]
お世話になっております。
回答ありがとうございます。

録画開始時間と空フォルダーの件は，承知しました。

録画スケジュールをスキップする件については，

・ATOMCam Hack のスケジュール録画とは，製品アプリの時間帯検出で
　曜日と時間帯を設定するのと同じ機能なのでしょうか。
　そうであれば，モーション検知と無関係に設定した時間帯を録画する機能を
　求めていたので，当方の認識違いということになるかと思います。
　元の製品の機能とは異なる点があればご教授いただければ幸いです。

・先ほどご報告した結果は，モーション検知はOFFで稼働させたものです。

・スケジュール録画　モーション検知が必須だとすれば，本体のこの機能の不安定さは
　ネット上にいくつかあがっていた様に思いますので，そのせいかもしれませんね。

　・録画がスキップされた設定３は，録画されていた設定１，設定２，設定４と
　　時刻以外は全くの同一条件で，画角内に動きが検知されるような被写体ではなく，
　　音についてもほとんど変わりがないはずです。特に設定５については，就寝後の
　　深夜のため非常に静かであったと思われます。

　・音を含めたモーション検知がスケジュール録画の必要条件だとすると
　　録画されていたものすべての開始時刻がスケジュールとほぼ合致している点も
　　動作の因果関係が整合していないように思います。
　　スケジュール録画でモーション検知が必要なら録画開始時刻は検知された時刻に
　　なるのではないでしょうか。
　　（上述のように，常に音検知がされるような音環境下でのテストでは
　　　ありませんでした。）

よろしくお願いします。

**Comment by mnakada** [comment]
連続録画の録画スケジュールはAtomCamのFW側で連続録画としてSD-Cardに記録してくるmp4ファイルを指定時間でフィルターする機能です。
アプリの時間帯検出はモーション検知の時間設定で12秒の録画の制限だと思います。

指定時間の全てを記録したい場合はアプリの録画モードを連続録画に設定する必要があります。
ここをモーション検知時のみにするとモーション検知がoffでも記録されるmp4ファイルはモーション検知した時のみ記録されるようです。

**Comment by otatm** [comment]
お世話になっております。
早速のご回答ありがとうございます。

本体アプリの録画モードは連続録画にしています。
（"モーション検知時のみ"にはしていません。）
ご説明のようにSDカード書き込み時にatomcam_toolsで指定時間でフィルタリングする
のであれば，フィルター処理がうまく機能していないという事にならないでしょうか。

よろしくお願いします。

**Comment by mnakada** [comment]
sshでloginして
cat /atom/config/.usr_config
の結果を貼ってもらえますか

**Comment by otatm** [comment]
返信ありがとうございます。
SSHを使ったことがないので，少しお時間をいただきたいと思います。
よろしくお願いします。

**Comment by otatm** [comment]
お世話になっております。

何とかログインできたので，ご指定のファイルの内容を記載します。
なお，明らかに公開してはマズそうな情報　[NET]，[CAMERA_INFO]は
内容を削除させていただきました。

よろしくお願いします。

[root@atomcam:configs]# pwd
/atom/configs
[root@atomcam:configs]# cat .user_config
[SETTING]
AddInfoSwitch=2
WLSwitch=0
kvsModelType=0
secondtimezone=32400
TrackSwitch=2
motor_speed=5
TotalSwitch=2
PetsSwitch=1
PeopertySwitch=1
night_cut_thr=1
cloudSwitch=2
autoBitrate=2
voiceScene=1
voiceSwitch=2
sdevAction=1
alarmInterval=300
alarmDate=254
dongleLight=1
recordSize=0
recordNum=0
sdeviceExist=0
nightLight=1
pir_alaram=1
speaker_vol=50
watermark_flag=1
low_bitrate=30
motor_limit=0
limit_min_y=0
limit_max_y=0
limit_min_x=0
limit_max_x=0
exposureModel=0
ubootflag=0
preset_y=0
preset_x=0
slide_y=0
slide_x=0
motionback=1
AALY=50
AALX=50
AASY=25
AASX=25
motionCruisin=2
motionTrack=2
AST=1
MAT=0
AMALevel=128
MMALevel=128
timezone=9
drawBoxSwitch=2
TBDuration=1440
TBStart=900
CASwitch=2
SASwitch=2
AALevel=5
AASwitch=2
MALevel=5
MASwitch=2
recordType=1
telntSwitch=2
logUdisk=1
logSd=1
osdSwitch=1
verSwitch=1
horSwitch=1
fps=20
res=1
bitRate=30
nightVision=3
indicator=1

[NET]
bindOk=　（非表示）
p2pid=　（非表示）
r_encr=　（非表示）
password=　（非表示）
ssid= （非表示）

[CAMERA_INFO]
p2pServerAddr=EDGG・・（非表示）
CRCKey=:　（非表示）
[root@atomcam:configs]#

**Comment by mnakada** [comment]
ありがとうございます。
設定は正しく反映されてますね。

ちょっとlogを取って貼ってもらえますか

sshでloginしたところで
touch /media/mmc/atom-log
sync
reboot
を実行して再起動します。これでlogを取る機能がonになります。

もう一度sshでlogin
tail -F /tmp/log/atom.log
で見ていると下記のようなlogが出てくると思います。
```
[record.c,1028]dbg:(record_file_open) curRelFileName: /media/mmc/record/20240519/22/27.mp4
[mp4] mp4write_start_handler  v fps:25
[mp4] mp4write_start_handler  v enc:H.264
[mp4] mp4write_start_handler  v vp.maxstreamsize:327680
[mp4] mp4write_start_handler  a sampleRate:8000
[mp4] mp4write_start_handler  a enc:G711
[continueRec]dbg: recordAudio switch:1 (before)
[exec-iCame,0471](no.100000) msgque ret:[0]
[watchdog]dbg: watchdog_snd_msg_feed [time:1716125236]
[watchdog]dbg: watchdog_snd_msg_feed [time:1716125266]
[continueRec]dbg: (continue_record_task_worker) time full, break...
[continueRec]dbg: recordAudio switch:1 (after)
[mp4]1dbg: mp4write_stop_handler ret:0, id = 0
[mp4]dbg: mp4write_stop_handler endCallbackFn doing...
(record_stop_finish_callback) in...
[exec-iCame,0468](no.100000) cmd:[mv /tmp/27.mp4 /media/mmc/record/20240519/22/27.mp4;sync;echo 1 > /proc/sys/vm/drop_caches]
[mp4]2dbg: mp4write_stop_handler ret:0
[mp4]3dbg: mp4write_stop_handler ret:0
[sdevice.c,0092]### (sdevice_get_space) [total:124908339200][free:113912086528][used:10996252672] ###
[continueRec]dbg: rolldel success!
```
上記が連続記録の1分間（22/27.mp4）の記録時のlogです。
記録されなかった時の状態を見たいので、記録されなかった時間の部分のlogを貼ってもらえますか。

**Comment by otatm** [comment]
確認ありがとうございました。

できれば明日，ログが取れる状態にしてスケジュール録画をやり直してみます。
ご報告まで少し時間がかかると思いますが，お待ちいただければ幸いです。

よろしくお願いします。

**Comment by otatm** [comment]
お世話になっております。
ログをとりながら前回に準じた5段階のスケジュール録画を試してみましたが，スケジュールをスキップしてしまう現象は見られませんでした。
設定したスケジュールは，以下のとおりです。

【設定１】月～日（全日） 22:40～22:42
　　録画（mp4）　22:39～22：42　ファイル数 3　　
【設定２】月曜　　　　　 22:45～22:48
　　録画（mp4）　22:44～22：48　ファイル数 4　　
【設定３】月～日（全日） 23:05～23:07
　　録画（mp4）　23:04～23：07　ファイル数 3　　
　　（前回，設定どおりに録画されなかった設定です）
【設定４】火曜　　　　　 23:10～23:12
　　録画（mp4）　なし
【設定５】月～日（全日） 23:15～23:18
　　録画（mp4）　23:14～23：18　ファイル数 4

記録されなかったスケジュールがなかったのでログは張らないでおきます。

しばらく動作確認をしたいところですが，すぐにでもスケジュール運用をしたい事情があるため，恐縮ながら今回は電源側にスケジュールタイマーを付けることで対応したいと思います。
ここまで大変丁寧にご対応いただいたにも関わらず，相談した側が投げ出すような形となってしまい大変心苦しいのですが，ご理解いただければ幸いです。

これまで本当にありがとうございました。
今後ともよろしくお願いいたします。
