### ISSUE TITLE
Timelapseの時間を夜間も設定できるようにしてほしい。

### ISSUE THREAD

**Issue by ehjivh** [mnakada/atomcam_tools#102]
いつも大変お世話になっております。すばらしいツールの作成、公開頂き非常に感謝しております。
Timelapse機能について20:00までとなっておりますが、星空を撮影するために、夜間に撮影する場合の設定ができるようにして頂ければと思います。
お手数をおかけしますが、よろしくお願いします。

**Comment by mnakada** [comment]
タイムラプスの時間設定は開始時刻と周期x回数で終了時間が計算されます。
20:00までという時間制限はありません。

**Comment by ehjivh** [comment]
ご返信、ご教示頂きありがとうございます。こちらの勘違いでした。開始時間を変更したところ、要望通りの挙動をしてくれまいした。痒い所に手が届くすばらしいツールを本当にありがとうございます。
