### ISSUE TITLE
検知録画のNASとSDカード保存時にファイル名に使われる時刻を一致させたい

### ISSUE THREAD

**Issue by paki2890** [mnakada/atomcam_tools#104]
素晴らしいツールありがとうございます。LAN内にファイルを保存できるカメラを探してこちらのツールにたどり着きました。

NASとSDカード両方保存の設定で、NASがオフライン中に保存できなかった欠落ファイルを後でSDカードから吸い出す使い方をしたいのですが、atom_patch/bin/rmのスクリプトが「dateでファイル名を作成してNASコピー→dateでファイル名を作成してSDカードコピー」という順なので、NASとSDカードで同じファイルのファイル名が1-2秒分ズレることがあって、欠落の確認が厄介になっています。
下記のように時間を一旦保存してから使いまわせばファイル名を一致させることができて便利になるのですが、ご検討願えますか？

```
  if [ "$FMT" != "" ] ; then
    NOW = `date +%Y%m%d%H%M.%S`
    if [ "$ALARMREC_CIFS" = "on" ] && /tmp/system/bin/mount_cifs.sh ; then
      CIFSFILE=`date -d $NOW +"alarm_record/$ALARMREC_CIFS_PATH.${FILE##*.}"`
略
    if [ "$ALARMREC_SDCARD" = "on" ]; then
      SDCARDFILE=`date -d $NOW +"alarm_record/$ALARMREC_SDCARD_PATH.${FILE##*.}"`
```

**Comment by mnakada** [comment]
わかりました。次のリリースで修正します。

**Comment by mnakada** [comment]
Ver.2.5.2で修正しました。

**Comment by paki2890** [comment]
時刻が合うようになりました。
ご対応ありがとうございました。
