### ISSUE TITLE
タイムラプス録画も複数設定できるようになりませんか。

### ISSUE THREAD

**Issue by Masakai** [mnakada/atomcam_tools#105]
録画設定と同様に、タイムラプスも複数パターンの設定をできるようになりませんか？

**Comment by Masakai** [comment]
設定内容は現状のタイムラプスと同じで良いのですが、複数のタイムラプスを設定したいので
タイムラプス設定画面のサンプリング設定において録画設定画面のスケジュール設定にあるように　＋ー　でサンプリング設定のパターンが増やせるようになると嬉しいです。

要は、朝と夕方、深夜のような時間帯を複数設定できるような設定です。

**Comment by mnakada** [comment]
Ver.2.5.3で対応しました

**Comment by Masakai** [comment]
ありがとうございます！
