### ISSUE TITLE
画面に中央がわかるマークを表示できる機能

### ISSUE THREAD

**Issue by Hiii555** [mnakada/atomcam_tools#106]
こんにちは。2.5.2から実装された「画面に中央がわかるマークを表示できる機能」についてです。
保存画像（動画）にこのマークを表示させるorさせないスイッチが欲しいです。
目視の位置確認でズレなど確認できて良いのですが、保存画像にも欲しい方、欲しくない方選べるような形にできませんか。
![line](https://github.com/mnakada/atomcam_tools/assets/161435860/406c6151-6f69-44e7-b8a2-3ddb300b28b4)

**Comment by mnakada** [comment]
この機能は設置時に位置合わせするために作ったのですが、何か他の用途で使い道ありますか？
メインの映像に重畳されているので、onの状態のままなら映像にも記録されますが、WebUIの画面と記録の映像とをon/offを分けることはできないです。

**Comment by Hiii555** [comment]
それであれば仕様ですので使わない、使う時だけというユーザ側の使い方で調整するのでクローズします。
