### ISSUE TITLE
初代AtomcamにてWebUIのヘッダーが白い

### ISSUE THREAD

**Issue by accept** [mnakada/atomcam_tools#107]
お世話になっております。
いつも素晴らしいソフトウェアの提供、ありがとうございます。

いつからか分からないのですが、初代Atomcamにて下記画像のようにヘッダーが白になっているようです。
手持ちの初代がこの機種しかないので他の検証は出来ていないのですが、Swingや2では今まで通りの朱色の色が出ております。
これはうちだけの問題でしょうか。

![スクリーンショット 2024-06-04 152455](https://github.com/mnakada/atomcam_tools/assets/421679/2da380bd-10a3-4872-a3ae-6cb8bc937ce6)

今のところヘッダーの色以外目立った問題はないのですが、一応ご報告させていただきました。

**Comment by mnakada** [comment]
ありがとうございます。WyzeCam対応したときに初代ATOMの判別が抜けていました。
WebUIだけなので次回updateで修正します。

**Comment by accept** [comment]
なるほど、そうだったのですね。
ありがとうございます。

**Comment by mnakada** [comment]
Ver.2.5.3で修正しました

**Comment by accept** [comment]
@mnakada 
お世話になっております。
修正を確認しました。遅くなってしまい申し訳ありません。
ありがとうございました。
