### ISSUE TITLE
メディア設定、保存先にFTPやWebDAVの設定も追加できませんか？

### ISSUE THREAD

**Issue by akafuku-san** [mnakada/atomcam_tools#108]
とても使い勝手の良いツールの提供、ありがとうございます。
遠隔地のカメラのSDに保存されるデータ収集に使えないかと考えておりまして、希望を述べさせていただきました。

**Comment by mnakada** [comment]
FTPもWebDAVもセキュリティ的な問題でサポートがなくなってきているプロトコルで、検証環境もないため申し訳ありませんが対応できません。

**Comment by akafuku-san** [comment]
なるほど承知いたしました。ご回答ありがとうございます。

**Comment by mnakada** [comment]
closeします。
