### ISSUE TITLE
Ver.2.5.4後、イベント通知が来ない&モーション録画されていない

### ISSUE THREAD

**Issue by katsumiota** [mnakada/atomcam_tools#109]
mnakada様、こんばんは。
いつもツールを利用させて頂いています。ありがとうございます。

さて、どうやらVer.2.5.4後、「イベント通知」がこなくなったみたいです。モーション等の録画（検知）もされていません。尚、常時録画はキチンとされています。

お手数ですがご確認頂けますと幸いです。

**Comment by katsumiota** [comment]
先ほど確認のためVer.2.5.3に戻してみたところ問題なくモーション検知録画されてます。

**Comment by mnakada** [comment]
Ver.2.5.5で修正しました。

**Comment by katsumiota** [comment]
こんばんは。早速のご対応ありがとうございました。

**Comment by katsumiota** [comment]
mnakada様、こんにちは。思う一つお伝えするのを忘れていましたので、書き込みさせてください。
Ver.2.5.4でモーション検知されない問題は解決致しましたが、カメラリセットを実行したときの動作？が変です。表現が難しいのですが、リセットすると2回斜め下にカメラアングルが動いて定位置（基準位置？）に戻る感じです。普通は1回だけだったかと思います。
立て続けに2回カメラリセットを実行したときの様な動きです。

お手数ですがまたご確認頂けますでしょうか？

**Comment by mnakada** [comment]
これは追加した意図的な動きです。
ATOM Swingの元々の動作の場合、反対側の端点への動作がないため座標がずれていることが多々発生していたため、反対側の端点まで移動する動作を追加しています。
これによってある程度正確な座標が実現できます。

**Comment by katsumiota** [comment]
> これは追加した意図的な動きです。 ATOM Swingの元々の動作の場合、反対側の端点への動作がないため座標がずれていることが多々発生していたため、反対側の端点まで移動する動作を追加しています。 これによってある程度正確な座標が実現できます。


こんにちは。意図的な動きだったのですね、全く知らなくて失礼致しました。ありがとうございました。
