### ISSUE TITLE
atomcam_toolへのPOST連動をしたい、ナイトビジョン用赤外線ライト、スリープ。

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#11]
AtomCamのアプリで手動設定は可能なのですが他システムとの連動ができるとありがたいです。

ナイトビジョン用赤外線ライト、スリープについては人感センサーと連動してクライアントからpostで
コマンドを送信しon/offできればありがたいと思っています。

利用シーンは次のように考えています。

１．夜間でも街灯の照明があればきれいに映るのですが、照明が当たらない場所へ被写体が近づくと明瞭に映らないため、
撮影したいエリア付近に人感センサーを設置し、その反応によりナイトビジョン用赤外線ライトをONする命令をpostし
atom cam の赤外線ライトを点灯させると、被写体が明瞭に映るのではと思います。適当な時間でOFFする命令をpostし消灯します。

２．カメラの映像をファイルサーバーに録画しているのですが、時間帯によってクライアントからのpostで
録画が不要なカメラをスリープにするとファイルサーバーの容量を効率的に利用できるかと思います。

NAS録画／NASモーション検知録画の機能提供、ありがとうございます。
ディスクの必須容量ですが、
1分8MB×60m×24h=11520MB
カメラ1台、1日　11.52GB
10日連続保存確保として、115.2GB
4台同時保存で　460.8GB　となります。
1TBのHDDにLinuxをインストールした場合　/home　に850GB程度確保することができます。

計算上は4台で約20日、計算上は8台で約10日程度　連続録画できると思われます。

alert録画も併用するとその容量分、連続録画できる時間が短くなります。

具体的な希望としては
１．Web設定画面 へのスイッチ追加

機能設定
ナイトビジョン用赤外線ライトのON/OFF
スリープのON/OFF

２．apiの追加
postするコマンドの例こんな感じでしょうか　お任せします。
{"exec":"Infrared light", "sw": "on"}
{"exec":"Infrared light", "sw": "off"}

{"exec":"sleep", "sw": "on"}
{"exec":"sleep", "sw": "off"}

ソースを拝見し勉強させていただいております、プルリクエスト出来るように精進いたします。
ご検討の程よろしくお願いします。

**Comment by mnakada** [comment]
> ナイトビジョン用赤外線ライトのON/OFF

検討して見ますが、ちょっと時間かかりそうです。

> スリープのON/OFF

iCamera_appの構造上hook pointが見当たらず、アプリと同等のスリープ機能は難しいです。
目的はSD-CardやNASへの記録を外部からのAPIで停止することかと思うので、代替手段を検討してみます。

**Comment by kurokouji** [comment]
思いついたこと無茶ぶり申しわけありません。
お時間のある時で構いません、当方iCamera_appの構造まで理解していませんので回答いただけるだけで感謝いたします。
ナイトビジョン用のON/OFFの代わりに、人感センサーつきの照明器具の取り付けでも対策できます。
スリープ機能のコントロールにこだわるよりもSD、NASへの録画コントロールで実現できますね。
検討頂きありがとうございます。

**Comment by mnakada** [comment]
Ver.1.2.22で赤外線LED(night mode)のon/off/autoの切り替えに対応しました。
curlの場合下記で確認しています。
```
curl -X POST -H 'Content-Type: application/json' -d '{"exec":"irled on"}' --output - 'http://atomcam.local/cgi-bin/cmd.cgi?port=socket'
```

**Comment by kurokouji** [comment]
Ver.1.2.22 確認いたしました。
赤外線LEDがWebUI画面からコントロールできるようになり操作性も良いです。
画像のすぐ下に配置されたボタンも直感的で使いやすいです。
curlによるコントロールも確認しました、ありがとうございます。

**Comment by kurokouji** [comment]
Ver.1.3.2 更新いたしました、フォルダへのアップロードファイル有無、確認しました。
[centos@localhost ~]$ curl -X POST -H 'Content-Type: application/json' -d '{"exec":"cifsaccess disable"}' http://192.168.100.46/cgi-bin/cmd.cgi
cifsaccess disable OK
[centos@localhost ~]$ curl -X POST -H 'Content-Type: application/json' -d '{"exec":"cifsaccess enable"}' http://192.168.
100.46/cgi-bin/cmd.cgi
cifsaccess enable OK
[centos@localhost ~]$ 
いつもありがとうございます。
