### ISSUE TITLE
Changing time zone

### ISSUE THREAD

**Issue by orizzle** [mnakada/atomcam_tools#110]
Hello, I am located in the USA.  I am looking for an easy way to change the timezone.  For each release, I have to unpack the squashfs and remove /etc/environment so the time gets set to UTC.  Is there an easier way?

**Comment by mnakada** [comment]
OK, I understand.
I will add a way to set the timezone in the next release.

**Comment by orizzle** [comment]
> OK, I understand. I will add a way to set the timezone in the next release.

thank you! amazing work you are doing
