### ISSUE TITLE
動体検知周期の短縮（30秒に短縮）について

### ISSUE THREAD

**Issue by R163-sayu** [mnakada/atomcam_tools#111]
mnakada様
いつもお世話になっております。
ツールを利用させていただきありがとうございます。
最近になって気付いたのですが、動体検知周期の短縮（30秒に短縮）が有効になっていない様子です。
誠にお手数お掛けし申し訳ございませんが、お確かめいただけますでしょうか。
宜しくお願い致します。

**Comment by mnakada** [comment]
機種名とATOMCamのVerとtoolsのVerを教えてください。

**Comment by R163-sayu** [comment]
お世話になります。
機種名は、AtomCAM2です。
色々調べてみたところ、AtomCAM2本体のファームウェアを4.58.0.139にupdateしたことが原因のようでした。
このファームウェアでatomcam toolのver.を2.5.5、2.5.6、2.5.7にして確かめましたが、
動体検知周期の短縮（30秒に短縮）が有効となりませんでした。
AtomCAM2本体のファームウェアを古いver.に戻してみたいと思います。
大変お騒がせしました。
