### ISSUE TITLE
recordディレクトリに意図せず分毎のjpeg

### ISSUE THREAD

**Issue by km5291jp** [mnakada/atomcam_tools#113]
アップデート後に症状が出ました。toolsを先に2.5.8に更新した後にfwを4.58.0.139に更新。
常時録画off、タイムラプスを時間帯指定、タイムラプス動いてない時間帯でもjpegが分毎にrecordディレクトリに生成されているみたいです。tools由来なのか不明ですがissueしておきます。

> [root@atom:~]# ls /media/mmc/record/20240828/07
> 00.jpeg  04.jpeg  08.jpeg  12.jpeg  16.jpeg  20.jpeg  24.jpeg  28.jpeg  32.jpeg  36.jpeg  40.jpeg  44.jpeg  48.jpeg  52.jpeg  56.jpeg
> 01.jpeg  05.jpeg  09.jpeg  13.jpeg  17.jpeg  21.jpeg  25.jpeg  29.jpeg  33.jpeg  37.jpeg  41.jpeg  45.jpeg  49.jpeg  53.jpeg  57.jpeg
> 02.jpeg  06.jpeg  10.jpeg  14.jpeg  18.jpeg  22.jpeg  26.jpeg  30.jpeg  34.jpeg  38.jpeg  42.jpeg  46.jpeg  50.jpeg  54.jpeg  58.jpeg
> 03.jpeg  07.jpeg  11.jpeg  15.jpeg  19.jpeg  23.jpeg  27.jpeg  31.jpeg  35.jpeg  39.jpeg  43.jpeg  47.jpeg  51.jpeg  55.jpeg  59.jpeg
> 

> [root@atom:~]# ps -wl
> S   UID   PID  PPID   VSZ   RSS TTY   STIME TIME     CMD
> S     0     1     0  2828   720 0:0   07:42 00:00:00 init
> S     0     2     0     0     0 0:0   07:42 00:00:00 [kthreadd]
> S     0     3     2     0     0 0:0   07:42 00:00:00 [ksoftirqd/0]
> S     0     5     2     0     0 0:0   07:42 00:00:00 [kworker/0:0H]
> S     0     7     2     0     0 0:0   07:42 00:00:01 [rcu_preempt]
> S     0     8     2     0     0 0:0   07:42 00:00:00 [rcu_bh]
> S     0     9     2     0     0 0:0   07:42 00:00:00 [rcu_sched]
> S     0    10     2     0     0 0:0   07:42 00:00:00 [watchdog/0]
> S     0    11     2     0     0 0:0   07:42 00:00:00 [khelper]
> S     0    12     2     0     0 0:0   07:42 00:00:00 [kdevtmpfs]
> S     0    13     2     0     0 0:0   07:42 00:00:00 [writeback]
> S     0    14     2     0     0 0:0   07:42 00:00:00 [bioset]
> S     0    15     2     0     0 0:0   07:42 00:00:00 [kblockd]
> S     0    16     2     0     0 0:0   07:42 00:00:00 [khubd]
> S     0    17     2     0     0 0:0   07:42 00:00:03 [kworker/0:1]
> S     0    18     2     0     0 0:0   07:42 00:00:00 [cfg80211]
> S     0    19     2     0     0 0:0   07:42 00:00:00 [kworker/0:2]
> S     0    20     2     0     0 0:0   07:42 00:00:00 [kswapd0]
> S     0    21     2     0     0 0:0   07:42 00:00:00 [fsnotify_mark]
> S     0    22     2     0     0 0:0   07:42 00:00:00 [crypto]
> S     0    36     2     0     0 0:0   07:42 00:00:00 [kworker/u2:1]
> S     0    38     2     0     0 0:0   07:42 00:00:00 [deferwq]
> S     0    43     2     0     0 0:0   07:42 00:00:01 [mmcqd/0]
> S     0    48     2     0     0 0:0   07:42 00:00:00 [kworker/0:1H]
> S     0    54     2     0     0 0:0   07:43 00:00:00 [loop0]
> S     0    72     1  2828   668 0:0   07:43 00:00:00 /sbin/syslogd -n
> S     0    73     1  2828   692 0:0   07:43 00:00:00 /sbin/klogd -n
> S  1001    93     1  3132   960 0:0   07:43 00:00:00 dbus-daemon --system
> S     0   112     2     0     0 0:0   07:43 00:00:00 [loop1]
> S     0   118     2     0     0 0:0   07:43 00:00:00 [loop2]
> S     0   123     2     0     0 0:0   07:43 00:00:00 [loop3]
> S     0   149     1  2944   772 0:0   07:43 00:00:00 /usr/sbin/crond -l 8
> S     0   169     2     0     0 0:0   07:43 00:00:00 [phy0-atbm_wq]
> S     0   170     2     0     0 0:0   07:43 00:00:00 [phy0-atbm_bh]
> S     0   171     2     0     0 0:0   07:43 00:00:02 [phy0-sdio_tx]
> S     0   172     2     0     0 0:0   07:43 00:00:09 [phy0-sdio_rx]
> S     0   173     2     0     0 0:0   07:43 00:00:01 [ksdioirqd/mmc1]
> S     0   193     1  5824  1412 0:0   07:43 00:00:00 wpa_supplicant -f /tmp/log/wpa_supplicant.log -D nl80211 -i wlan0 -c /configs/
> S     0   204     2     0     0 0:0   07:43 00:00:00 [kworker/u2:3]
> S     0   214     1  2828   208 0:0   07:43 00:00:00 udhcpc -i wlan0 -b
> S     0   240     1  3256   528 0:0   07:43 00:00:00 /usr/sbin/ntpd -p ntp.nict.jp
> S     0   251     1  5800   796 0:0   07:43 00:00:00 /usr/sbin/sshd
> S     0   257     1  2828   640 0:0   07:43 00:00:00 {webhook.sh} /bin/sh /scripts/webhook.sh
> S     0   262   257  2828   860 0:0   07:43 00:00:00 awk  BEGIN {  FS  = "= ;   while(getline <HACK_INI ) {    ENV [$1]=$2;   }  FS
> Z     0   264   262     0     0 0:0   07:43 00:00:00 [sh]
> S     0   297     2     0     0 0:0   07:43 00:00:01 [irq/37-isp-m0]
> S     0   299     2     0     0 0:0   07:43 00:00:00 [irq/38-isp-w02]
> S     0   339     1 18320   952 0:0   07:43 00:00:05 /system/bin/hl_client
> S     0   340     1  804m 23152 0:0   07:43 00:05:33 /system/bin/iCamera_app
> S     0   351     1 96048  2052 0:0   07:43 00:00:02 /system/bin/assis
> S     0   414     1  1592   440 0:0   07:43 00:00:00 {sysMonitor.sh} /bin/sh /system/bin/sysMonitor.sh
> D     0   436     2     0     0 0:0   07:43 00:00:35 [isp_fw_process]
> S     0   552     1  2828   620 0:0   07:43 00:00:00 {webcmd.sh} /bin/sh /scripts/webcmd.sh
> S     0   562   552  2828   468 0:0   07:43 00:00:00 tail -F /var/run/webcmd
> S     0   563   552  2828   312 0:0   07:43 00:00:00 {webcmd.sh} /bin/sh /scripts/webcmd.sh
> S  1000   566     1  3712  1760 0:0   07:43 00:00:00 avahi-daemon: running [atom-kz.local]
> S    33   592     1  3552  1288 0:0   07:43 00:00:05 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
> S     0   615     1  2892   676 ttyS1 07:43 00:00:00 /sbin/getty -L ttyS1 115200 vt100
> S     0   701     1 31492  6124 0:0   07:43 00:00:00 smbd -D
> S     0   703   701 29400  2196 0:0   07:43 00:00:00 smbd -D
> S     0   722   701 31492  2256 0:0   07:43 00:00:00 smbd -D
> S     0   749     1 19340  2376 0:0   07:43 00:00:00 nmbd -D
> S     0  1313   701 32348  6948 0:0   07:46 00:00:02 smbd -D
> R     0  1536   251  8360  2652 0:0   07:58 00:00:00 sshd: root@pts/0
> S     0  1558  1536  3008   940 pts0  07:58 00:00:00 -sh
> S     0  2333     2     0     0 0:0   07:58 00:00:00 [kworker/u2:0]
> S     0  3037   414  1584   292 0:0   08:02 00:00:00 sleep 5
> Z     0  3041   149     0     0 0:0   08:02 00:00:00 [sh]
> Z     0  3042   149     0     0 0:0   08:02 00:00:00 [sh]
> Z     0  3044   149     0     0 0:0   08:02 00:00:00 [sh]
> Z     0  3045   149     0     0 0:0   08:02 00:00:00 [sh]
> S     0  3107     2     0     0 0:0   08:02 00:00:00 [kworker/u2:2]
> R     0  3124  1558  2892   728 pts0  08:03 00:00:00 ps -wl
>

**Comment by mnakada** [comment]
録画モードの設定がおかしいですね。
次のupddateで修正します。

**Comment by mnakada** [comment]
Ver.2.5.9で修正しました。

**Comment by km5291jp** [comment]
まだ出ているみたいです。
```console
# date;ls /media/mmc/record/20240901/06/
Sun Sep  1 06:06:48 UTC 2024
00.jpeg  01.jpeg  02.jpeg  03.jpeg  04.jpeg  05.jpeg  06.jpeg
```
どこかチェックしたほうが良いところありますか?
(実質、たいして問題とはならないと思うので優先度低で...)
```console
# cat /atom/media/mmc/hack.ini
CONFIG_VER=1.0.2
appver=4.58.0.139
ATOMHACKVER=2.5.9
PRODUCT_MODEL=ATOM_CamV3C
HOSTNAME=***
HWADDR=7C:DD:E9:06:BC:72
DIGEST=
REBOOT=off
REBOOT_SCHEDULE=0 2 * * 0
RTSP_VIDEO0=off
RTSP_AUDIO0=off
RTSP_VIDEO1=off
RTSP_AUDIO1=off
RTSP_VIDEO2=off
RTSP_AUDIO2=off
RTSP_OVER_HTTP=off
RTSP_AUTH=off
RTSP_USER=
RTSP_PASSWD=
HOMEKIT_ENABLE=off
HOMEKIT_SETUP_ID=***
HOMEKIT_DEVICE_ID=***
HOMEKIT_PIN=***
HOMEKIT_SOURCE=rtsp://localhost:8554/video0_unicast
RTMP_ENABLE=off
RTMP_URL=
WEBRTC_ENABLE=off
PERIODICREC_SDCARD=off
PERIODICREC_SDCARD_REMOVE=on
PERIODICREC_SDCARD_REMOVE_DAYS=14
PERIODICREC_CIFS=off
PERIODICREC_CIFS_PATH=%Y%m%d/%H%M%S
PERIODICREC_CIFS_REMOVE=off
PERIODICREC_CIFS_REMOVE_DAYS=30
PERIODICREC_SCHEDULE=off
PERIODICREC_SCHEDULE_LIST=[index_01];Rule=98;ContinueTime=1440;StartTime=0;Status=1;DelFlags=1;
ALARMREC_SDCARD=off
ALARMREC_SDCARD_PATH=%Y%m%d/%H%M%S
ALARMREC_SDCARD_REMOVE=on
ALARMREC_SDCARD_REMOVE_DAYS=14
ALARMREC_CIFS=off
ALARMREC_CIFS_PATH=%Y%m%d/%H%M%S
ALARMREC_CIFS_REMOVE=off
ALARMREC_CIFS_REMOVE_DAYS=30
ALARMREC_SCHEDHULE=on
ALARMREC_SCHEDULE_LIST=[index_01];Rule=0;ContinueTime=1;StartTime=0;Status=1;DelFlags=1;
TIMELAPSE_SDCARD=on
TIMELAPSE_SDCARD_PATH=%Y%m%d%H%M
TIMELAPSE_SDCARD_REMOVE=on
TIMELAPSE_SDCARD_REMOVE_DAYS=14
TIMELAPSE_CIFS=off
TIMELAPSE_CIFS_PATH=%Y%m%d%H%M
TIMELAPSE_CIFS_REMOVE=off
TIMELAPSE_CIFS_REMOVE_DAYS=30
TIMELAPSE_SCHEDULE=40 4 * * 1:2:3:4:5:6:0 /scripts/timelapse.sh start 6 1000;15 15 * * 1:2:3:4:5:6:0 /scripts/timelapse.sh start 6 2400;
TIMELAPSE_FPS=20
STORAGE_SDCARD_PUBLISH=on
STORAGE_SDCARD_DIRECT_WRITE=off
STORAGE_CIFSSERVER=
STORAGE_CIFSUSER=
STORAGE_CIFSPASSWD=
WEBHOOK_URL=
WEBHOOK_INSECURE=off
WEBHOOK_ALARM_EVENT=off
WEBHOOK_ALARM_INFO=off
WEBHOOK_ALARM_VIDEO_FINISH=off
WEBHOOK_ALERM_VIDEO=off
WEBHOOK_ALARM_PICT_FINISH=off
WEBHOOK_ALERM_PICT=off
WEBHOOK_RECORD_EVENT=off
WEBHOOK_TIMELAPSE_START=off
WEBHOOK_TIMELAPSE_EVENT=off
WEBHOOK_TIMELAPSE_FINISH=off
CRUISE=off
CRUISE_LIST=
MINIMIZE_ALARM_CYCLE=off
AWS_VIDEO_DISABLE=off
CUSTOM_ZIP=off
CUSTOM_ZIP_URL=
MONITORING_NETWORK=on
MONITORING_REBOOT=on
HEALTHCHECK=off
HEALTHCHECK_PING_URL=
LOCALE=ja
FRAMERATE=18
BITRATE_MAIN_AVC=960
BITRATE_SUB_HEVC=-180
BITRATE_MAIN_HEVC=-800
ALARMREC_SCHEDULE=off

```

**Comment by mnakada** [comment]
すみません。言葉足らずでした。
録画モードの値が正しく保存されておらず、Ver.2.5.8にした時にWebUIの初期値の連続録画に変更されてしまうというbugです。
録画モードの設定を元に戻してもらうと正常になると思います。

**Comment by km5291jp** [comment]
WebUIの[カメラ設定][検出設定][録画モード]の3択(連続|検知時|オフ)が更新時に連続になっていたのですね。
気が付きませんでした、失礼しました。ありがとうございました!
「オフ」で出力されなくなりました。

そうかここを「連続」に設定するとモーション検知on/offによらずに分毎で静止画が保存されるのですね。機能が把握出来ていなかったです。toolsとてもありがたく使わさせてもらっていて多謝です!

**Comment by km5291jp** [comment]
👍
