### ISSUE TITLE
「感度調整」の設定について

### ISSUE THREAD

**Issue by R163-sayu** [mnakada/atomcam_tools#114]
mnakada様
いつもお世話になっております。
ツールを利用させていただきありがとうございます。

「カメラ設定」の「検出設定」「モーション検知」「感度調整」にて感度を「高」に設定しても画面切り替え後に「低」の設定に変わってしまいます。尚、「中」に設定すると「中」の設定、「低」に設定すると「低」の設定が維持されていました。
アプリ側の感度設定には変化が見られなかったため、Hackの感度設定とアプリの感度設定が連動していないように見えます。恐れ入りますがご確認よろしくお願い致します。

モデル名；AtomCAM2
ファームウェア：4.58.0.139

**Comment by mnakada** [comment]
Ver.2.5.10で修正しました。

**Comment by R163-sayu** [comment]
早々の修正ありがとうございました。
検知領域も見れるようにしてくださりありがとうございます。
