### ISSUE TITLE
/media/mmc/TZ string parsing breaks daylight savings time

### ISSUE THREAD

**Issue by orizzle** [mnakada/atomcam_tools#116]
S34timezone.env

echo $timezone | awk '{z=substr($0,1,3);f=substr($0,4,1);match($0,/[0-9:]+/);o=substr($0,RSTART,RLENGTH);l=RLENGTH;if((l>2)&&!match(o,/:/)){if(l%2)o="0"o;for(i=1;i<= l;i+=2){if(i!=1)s=s ":";s=s substr(o,i,2);};o=s;};printf("%s%s%s\n",z,f,o);}'

My timezone is EST5EDT (US eastern time with daylights savings time).  I have EST5EDT in /media/mmc/TZ and the code above sets the TZ variable to EST55

"TZ=EST5EDT date" in console works fine but camera video time is off

**Comment by mnakada** [comment]
I will fix in the next release.

**Comment by orizzle** [comment]
I can confirm it is working on 2.5.11 thank you

**Comment by mnakada** [comment]
Thanks for the confirmation.
