### ISSUE TITLE
火災/CO警報機音検知の設定について

### ISSUE THREAD

**Issue by R163-sayu** [mnakada/atomcam_tools#117]
mnakada様
いつもお世話になっております。
ツールを利用させていただきありがとうございます。

「カメラ設定」の「検出設定」「火災/CO警報機音検知」の設定がアプリ側の設定と連動していないようです。
大変恐れ入りますがご確認よろしくお願い致します。

モデル名；AtomCAM2
ファームウェア：4.58.0.139

**Comment by mnakada** [comment]
次のupdateで修正します。

**Comment by mnakada** [comment]
Ver.2.5.12で修正しました。

**Comment by R163-sayu** [comment]
ご対応ありがとうございました。
