### ISSUE TITLE
SDカードの空き容量の表示

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#120]
アプリのSDカード管理で空き容量を確認していますが、
atomcam_toolsのWebアプリで見ることができると有難いです。
ご検討宜しくお願い致します。

**Comment by mnakada** [comment]
次の

**Comment by kurokouji** [comment]
![image](https://github.com/user-attachments/assets/a04139a1-b542-4c85-b5af-e78a419eb0c3)
早速のUpdateありがとうございます。挿入しているmicroSD 32BG、64GB、128GB　で確認しました。
表示が空き容量ではなく使用済みが適切ではないかと思います。
私の環境だけでしょうか？ver2.5.15に更新したところ、9時間ほど時間が遅れ表示されるようになりました。
恐れ入りますがご確認ください。

**Comment by mnakada** [comment]
ありがとうございます。
Ver.2.5.16で修正しました。

**Comment by kurokouji** [comment]
修正ありがとうございました、空き容量の表示、時計の表示　問題ありません。
最近気が付きましたが、build.md　の更新も大変分かりやすくて助かります。

**Comment by kurokouji** [comment]
![image](https://github.com/user-attachments/assets/35c98f19-795f-493d-b96c-c397d6fb92fc)
些細なことですが、
SD内の動画を再生した際に、これまでの詳細情報は消えますが空き容量表示のみ残っているようです。
