### ISSUE TITLE
jpegファイル追加抑制機能について

### ISSUE THREAD

**Issue by R163-sayu** [mnakada/atomcam_tools#124]
いつもお世話になっております。
素晴らしいTOOLのご提供ありがとうございます。

Ver.2.5.14にて、recordディレクトリにjpegファイルが追加されるのを抑制する機能を
追加していただきましたが、SD-Card録画のrecordディレクトリを確認したところ、
まだjpegファイルが生成されていました。
この機能はNAS録画に特化した機能かも知れませんが、もしそのようでしたらSD-Card録画にも
同機能を追加いただけると幸いです。

ATOMCam Hack Ver.2.5.14
ATOM_CamV3C Ver.4.58.0.139

**Comment by mnakada** [comment]
JPEGファイルの抑制のフラグが再起動時に無効になっていたbugがありました。
次回updateで修正します。

**Comment by R163-sayu** [comment]
修正いただきありがとうございました。
