### ISSUE TITLE
自動削除の保存日数について

### ISSUE THREAD

**Issue by na-natsu-na** [mnakada/atomcam_tools#126]
お世話になります。
便利に使わせていただきましてありがとうございます。

表題の件でご質問がございます。
ファイルの自動削除ON、保存日数3日と全てで設定しているのですが、NASには5日分、SDカードには4日分や5日分残っていたりしています。
録画設定の画面で何度も「設定」ボタンを押していますが、計4台使っておりすべてのNAS、SDカードの録画ファイルでおきています。（record、alarm_record両方）
なにか設定が間違っているのかと思いますが、設定している保存日数になるヒントを教えて頂ければと思います。
お手数をおかけいたします。
よろしくお願いいたします。

atomcam_tools：2.5.17

ATOM CAM：4.33.3.73
ATOM CAM：4.33.3.73
ATOM CAM2：4.58.0.139
ATOM CAM SWING：4.37.1.152

![1](https://github.com/user-attachments/assets/a58ca94f-90ba-481d-97c2-b1c6b442e638)
![2](https://github.com/user-attachments/assets/e3390ab4-302d-4347-a8ed-ba5db20dad61)
![3](https://github.com/user-attachments/assets/7f61390c-080a-4a30-b30f-140639123b24)

**Comment by horixs** [comment]
正常な動作ですね。
以前に同じ質問を私がさせていただいた時の動作説明です。
こちらをお読みいただくと動作をご理解されると思います。

https://github.com/mnakada/atomcam_tools/issues/66#issuecomment-1363959678

**Comment by na-natsu-na** [comment]
返信ありがとうございます。
正常な動作とのこと承知いたしました。
一応、#66も読ませていただいたのですが
理解出来ずに同じ質問をしてしまいました。
申し訳ございませんでした。

NASの容量が少ないものですから、あまり多くは残しておきたくないものですから…
逆に言えば残しておきたい日数より1日少なく設定しておく必要があるのですね。
少し不思議な感じです…

ありがとうございました。

**Comment by na-natsu-na** [comment]
「保存したい日数ー１日」を設定する事で本来保存したい日数分の録画ファイルとなりました。
Closeとさせて頂きます。
ちゃんと過去分を読まずに失礼いたしました。
