### ISSUE TITLE
動体検知時のデータについて

### ISSUE THREAD

**Issue by hiroki-tagami** [mnakada/atomcam_tools#17]
AtomCAMでやりたいことを叶えてくださってありがとうございます。
早速使わせていただいているのですが、WebHookから送られてくるデータについて教えて下さい。

- やりたいこと
  -  アプリで動体検知すると、検知した種別(人、動物、動体 etc..)が拾えますが人の場合だけ取りたいです。

今回これを実現するためにWebHookを有効にして雑に作ったHTTPサーバで投げられるデータを確認していたのですが
`動体検知` と `動体認識情報` の JSONデータにある `data` の値がCSVで受信していますがこのデータはどういった意味を持つでしょうか？
このデータから動体種別を導くことは可能なのでしょうか？

**Comment by mnakada** [comment]
dataの意味ですが、順番に
認識している矩形の左下のX, Y, 右上のX,Y,　検知種別(0:不明/1:人/2:犬猫, 0固定(status?)
だと思われます。
（認識エンジンの中を解析したわけではないので、動作を見ての推測です）
ただし、認識精度はご存じのレベルなので外部で画像認識AI とか動かした方がいいと思います。

**Comment by hiroki-tagami** [comment]
早速のご返信ありがとうございます。
dataの意味についての、ご認識について回答ありがとうございました。
> 認識精度はご存じのレベルなので外部で画像認識AI とか動かした方がいい

確かに取得した画像を集めた上で自前学習やクラウドサービスで認識させるほうが精度も上がって
要件を満たせそうな気がします。ありがとうございました。
