### ISSUE TITLE
有線LANからもWEBAPP、sshでの接続が可能になるとありがたいです。

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#18]
有線LAN　OTG接続への対応お願いします。

ATOM Cam2にUSB-Ethernet変換アダプタを使って有線LANで使用する
https://honeylab.hatenablog.jp/entry/2021/06/26/235714
bakueikozo/atomcam_usbether　を試してみたところ問題なく動作しました。

atomcam_tools　が有線LANからも接続可能になると、無線LAN接続の不安定な件への対処が出来そうです。

接続に使用した機材は次の部品です。
但し、マイクロUSB端子の樹脂部分が厚いので、カッター等で削らないと、AtomCam2に挿できません。
https://www.amazon.co.jp/gp/product/B071D7XGPX/

こちらの商品だと加工は必要ありませんが取り寄せに時間が掛かります。
https://item.rakuten.co.jp/robotshopjapan/rb-adu-208/

ご検討の程よろしくお願いします。

**Comment by mnakada** [comment]
すみません。私は屋外設置しているので有線LANは興味の範囲外です。
実装してpull-reqしてくれればmargeを検討します。

**Comment by kurokouji** [comment]
回答ありがとうございます、pull-reqできるように精進にいたします。
