### ISSUE TITLE
WyzeにRTSP機能の説明か検討

### ISSUE THREAD

**Issue by virmaior** [mnakada/atomcam_tools#19]
突然の連絡ですみませんが、私は日本に住んでいるにも、atom知らず、wyzev3の５個を持ち、Wyzeは最近先に使ったハックをブロックしていました。それに応じて、@mnakadaさんの進化したatomcam_toolsに参考し、@gtaxspecさんはだいぶ似ているWyzeV3のSDだけにインスタールするツール・スクリプトを作っています。

その中に、RTSP機能も付けたいところですが、atomcamの方にあるiCameraとwyzeの方のiCameraはどこに異なるため、 wyzenにもて利用できるlibcallback.soはありうるかどうかを検討したいです。必要に応じて、Wyze3の１個をmnakadaさんへ配送できるかもしれません。

(英語にhttps://github.com/gtxaspec/wz_mini_hacks/issues/8で、同じことについて打てます。)

**Comment by mnakada** [comment]
https://github.com/gtxaspec/wz_mini_hacks/issues/8に回答しました。
以降、そちらで。
