### ISSUE TITLE
health checkサーバーへのhttp getの定期送信　バグ？

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#20]
AtomCam2　Ver.4.58.0.65
atomcam_tools　Ver.1.2.18

モニタリングの動作
Ping：ON
通知URL：http://192.168.1.43/index02.html
 
configs/overlay_rootfs/scripts/health_check.sh　を読み取ると次のような動作かと思っています。
１．通知URLをGETし、応答があればレスポンスをhealthcheck.logに書きこむ。
２．通知URLをGETし、応答が無ければ、1秒遅延し3回リトライし中断時間をhealthcheck.logに書きこみretry_countを+1する。
３．retry_countが3以上になったら、wlan0をdown/upする。
４．/media/mmc/atomhack.log　に　日時: WiFi restart　を書きこむ。

ローカルネットワーク上にalmalinuxサーバーを置き、apacheを起動し、
http://192.168.1.43/index02.html をgetすると　{"res":"OK"}を返すようにしています。
次healthcheck.log　の14:40:36 ～ 14:53:17　はサーバーのLANコネクタを外した状態です。
14:48:13　でwlan0をdown/up　し　atomhack.log　に日時: WiFi restartが記録されるのではないかと思いますが
何も出力されません。

動作確認時のログを送ります。
[root@atomcam:~]# tail -f /media/mmc/healthcheck.log
2022/04/18 14:35:31 : {"res":"OK"}
2022/04/18 14:36:32 : {"res":"OK"}
2022/04/18 14:37:33 : {"res":"OK"}
2022/04/18 14:38:34 : {"res":"OK"}
2022/04/18 14:39:35 : {"res":"OK"}
2022/04/18 14:40:36 :
2022/04/18 14:43:09 :
2022/04/18 14:45:41 :
2022/04/18 14:48:13 :
2022/04/18 14:50:45 :
2022/04/18 14:53:17 :
2022/04/18 14:55:49 : {"res":"OK"}
2022/04/18 14:56:53 : {"res":"OK"}

[root@atomcam:~]# tail -f /media/mmc/atomhack.log
             total       used       free     shared    buffers     cached
Mem:         74192      71200       2992          0         72      25700
-/+ buffers/cache:      45428      28764
Swap:       131068      14032     117036
Mon Apr 18 13:43:17 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      71420       2772          0         96      25496
-/+ buffers/cache:      45828      28364
Swap:       131068      14744     116324
1970/01/01 09:00:25 : Reboot & Start watchdog

確認のほどお願いいたします。
当方の勘違い、お気づきの点ありましたらお知らせください。

**Comment by mnakada** [comment]
ありがとうございます。
ちょっとおかしいですね。
再現実験をしているのですが、自分の環境では殆ど発生してなくて少し時間がかかりそうです。

**Comment by kurokouji** [comment]
ご確認いただきありがとうございます。
qiitaも拝見しております。

「qiita:ATOMCam2を少し改造して導入してみた
環境
build環境はMacOSMonterey上でDockerを使用していますが、特殊なことはしていないのでWindowsやlinuxでも大丈夫だと思います。」

を参考に開発環境を構築しようと思っておりますがなかなかうまくいきません。
当方にても実装・動作チェックを行いpull-reqしたいと思っておりますが、環境構築で足踏みしております。
開発環境の構築に参考になるような資料がありましたら紹介いただけないでしょうか。

**Comment by mnakada** [comment]
開発環境は何でしょうか？
docker, docker-composeは動作できていますか？
make.shを実行してエラー等は出ていますか？
docker, docker-composeの環境構築でしたらQiitaに色々な環境向けの記事が多数あるので検索してみてください。
私もMacOS monterey環境しか確認できていないので、もしかすると他の環境だとエラーになることもあるかもしれません。修正等あれば教えていただけると助かります。

**Comment by kurokouji** [comment]
開発環境はWindows10（32/64）Proです。
dockerは、数年前に動かしてこんなものかと思った程度で本格的には使ったことはありません。
そろそろ本格的に使用したいと思っている状況です。
まだmake.sh 試していません、その前の環境構築が無知な状況です。

>docker, docker-composeの環境構築でしたらQiitaに色々な環境向けの記事が多数あるので検索してみてください

恐れ入ります、検索しても、伝言ゲーム状態で、解りやすそうな記事があったら紹介して頂ければ助かります。

**Comment by mnakada** [comment]
Windowsを使ってないので適切な記事かわかりませんが、下記とかはどうでしょうか？
比較的新しい記事なので。
https://qiita.com/teruroom/items/a78e69249a43470d9f04

**Comment by kurokouji** [comment]
ご紹介いただき、ありがとうございます、勉強させていただきます。

**Comment by mnakada** [comment]
動作確認情報ありがとうございます。
wlan0のRx packet dropは多分CPU負荷の影響だと思います。
受信できたパケットが処理しきれずに捨てられているlogなので。
AiAlgoが動作した時の負荷がかなり高いのでそこの影響かと思いますが、あまりいい対応方法がないですね。
RAMが少なくてswap outされているのが根本的な原因かと思います。

**Comment by kurokouji** [comment]
Ver.1.2.20動作確認しました、また気づいた点ありましたらお知らせいたします。
参考までに　動作確認した　healthcheck.log　送ります。
１．2022/04/23 16:38:01　Ver.1.2.18　から　Ver.1.2.20　アップデート後
２．2022/04/23 16:41:24 : 000　apachサーバのLANを切断
３．2022/04/23 16:43:24 : WiFi restart　3回リトライ後、WiFi restart
４．2022/04/23 16:45:02 : 200　apachサーバのLANを復旧

[root@ck-cycle:~]# tail -f /media/mmc/healthcheck.log
2022/04/23 16:27:17 : {"res":"ok"}
2022/04/23 16:28:18 : {"res":"ok"}
2022/04/23 16:29:20 : {"res":"ok"}
2022/04/23 16:30:21 : {"res":"ok"}
2022/04/23 16:31:23 : {"res":"ok"}
2022/04/23 16:32:24 : {"res":"ok"}
2022/04/23 16:33:26 : {"res":"ok"}
2022/04/23 16:34:27 : {"res":"ok"}
2022/04/23 16:35:29 : {"res":"ok"}
2022/04/23 16:38:01 : 200
2022/04/23 16:39:01 : 200
2022/04/23 16:40:01 : 200
2022/04/23 16:41:24 : 000
2022/04/23 16:41:24 : retry : 1
2022/04/23 16:42:24 : 000
2022/04/23 16:42:24 : retry : 2
2022/04/23 16:43:24 : 000
2022/04/23 16:43:24 : retry : 3
2022/04/23 16:43:24 : WiFi restart
2022/04/23 16:44:24 : 000
2022/04/23 16:44:24 : retry : 1
2022/04/23 16:45:02 : 200
2022/04/23 16:46:02 : 200
2022/04/23 16:47:02 : 200

**Comment by mnakada** [comment]
ありがとうございます。
ちゃんと動いているようで安心しました。

**Comment by kurokouji** [comment]
いつも更新ありがとうございます。
Ver.1.2.21動作確認しました、大変良好に動作しています。

ファームの更新
AC2　ATOM_CAMV3C Ver.4.58.0.79
ACS　ATOM_CAKPJZJP Ver.4.37.1.95
とVer.1.2.20　以降、音信不通になる状況は皆無になりました。

当方の利用は、遠方（直線距離で721km）へSoftEtherVPNでトンネルを張り、4台のAtomCam2をモニタしています。
近隣でACS 1台、AC2 2台
音信不通になった場合に再起動するためスイッチボットプラグを設置、スイッチボットプラグも気まぐれにオフラインになるという現象が起きていました。
こちらの症状もVer.1.2.20、ファームの更新以降起きていません。

＊＊＊　些細な症状ですが、iPadでWebUIを開いた画面で更新ボタンが表示されません。それ以外は正常に機能しています。
＊＊＊　必要ならば、別にissuesを立て、画面コピーをアップします。

よろしくお願いします。

**Comment by mnakada** [comment]
確認ありがとうございます。

> ＊＊＊　些細な症状ですが、iPad（SafariとChromeで確認）でWebUIを開いた画面で更新ボタンが表示されません。それ以外は正常に機能しています。
＊＊＊　必要ならば、別にissuesを立て、画面コピーをアップします。

確認しますのでissueお願いします。

**Comment by kurokouji** [comment]
AtomCam2で音信不通が起きましたので参考までに報告いたします。
AtomCam2　Ver.4.58.0.79
atomcam_tools　Ver.1.2.21

2022/05/02 03:27:02　後Wifi接続が切れた様です。
2022/05/02 07:03:03　に電源再投入し復旧しました。

tmpfs　のfree値（30%から10%）が極端に下がってくるとWiFiが切れるようです。

提案、cpuは止まっていないようなので、任意の時間（10～60分程度）Wifiが不通の場合、
rebootするようにしてはいかがでしょうか。


healthcheck.log
2022/05/02 03:25:02 : 200
2022/05/02 03:26:02 : 200
2022/05/02 03:27:02 : 200
2022/05/02 03:28:29 : retry : 1
2022/05/02 03:29:20 : retry : 2
2022/05/02 03:30:16 : retry : 3
2022/05/02 03:30:16 : WiFi restart
2022/05/02 03:31:09 : retry : 1
2022/05/02 03:32:05 : retry : 2
2022/05/02 03:33:03 : retry : 3
2022/05/02 03:33:04 : WiFi restart

途中省略　retry :1,2,3　WiFi restart　繰り返し

2022/05/02 06:58:07 : retry : 1
2022/05/02 06:59:13 : retry : 2
2022/05/02 07:00:04 : retry : 3
2022/05/02 07:00:05 : WiFi restart
2022/05/02 07:01:03 : retry : 1
2022/05/02 07:02:07 : retry : 2
2022/05/02 07:03:02 : retry : 3
2022/05/02 07:03:04 : WiFi restart
2022/05/02 07:04:05 : retry : 1
2022/05/02 07:07:02 : 200
2022/05/02 07:08:02 : 200
2022/05/02 07:09:01 : 200
2022/05/02 07:10:01 : 200


atomhack.log
Mon May  2 03:00:01 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      69252       4940          0        472      20532
-/+ buffers/cache:      48248      25944
Swap:       131064      21064     110000
tmpfs                    37096     10868     26228  29% /tmp
Mon May  2 04:00:11 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      63664      10528          0        492      15272
-/+ buffers/cache:      47900      26292
Swap:       131064      20540     110524
tmpfs                    37096      3848     33248  10% /tmp
Mon May  2 05:00:11 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      66344       7848          0        576      14136
-/+ buffers/cache:      51632      22560
Swap:       131064      20192     110872
tmpfs                    37096      3784     33312  10% /tmp
Mon May  2 06:00:01 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      70984       3208          0       5304      13708
-/+ buffers/cache:      51972      22220
Swap:       131064      19704     111360
tmpfs                    37096      3756     33340  10% /tmp
Mon May  2 07:00:03 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      66184       8008          0        736      14868
-/+ buffers/cache:      50580      23612
Swap:       131064      19472     111592
tmpfs                    37096      3936     33160  11% /tmp
2022/05/02 07:03:03 : Reboot & Start watchdog
Mon May  2 08:00:00 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      71588       2604          0        672      24044
-/+ buffers/cache:      46872      27320
Swap:       131064      10840     120224
tmpfs                    37096     11052     26044  30% /tmp
Mon May  2 09:00:00 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      71456       2736          0        144      25484
-/+ buffers/cache:      45828      28364
Swap:       131064      15492     115572
tmpfs                    37096     10980     26116  30% /tmp

**Comment by mnakada** [comment]
ありがとうございます。
こちらもVer.1.2.22で対応しました。

**Comment by kurokouji** [comment]
Ver.1.2.22　更新いたしました。
しばらく観察してみます、また気づいた点ありましたら報告いたします。

**Comment by kurokouji** [comment]
reboot対応ありがとうございました。
Wifi切断後、30分で自動復旧しましたので報告いたします。
緊急性の少ないカメラからはスイッチボットプラグを撤収できそうです。
2.4GHz帯ではほぼ確実に電波干渉を起こしますので接続機器を減らすことができます。
healthcheck.log
2022/05/03 06:51:01 : 200
2022/05/03 06:52:01 : 200
2022/05/03 06:53:01 : 200
2022/05/03 06:54:18 : retry : 1
2022/05/03 06:55:16 : retry : 2
2022/05/03 06:56:14 : retry : 3
2022/05/03 06:56:16 : WiFi restart : error : 1
2022/05/03 06:57:06 : retry : 1
2022/05/03 06:58:01 : retry : 2
2022/05/03 06:59:01 : retry : 3
2022/05/03 06:59:01 : WiFi restart : error : 2
2022/05/03 07:00:07 : retry : 1
2022/05/03 07:01:04 : retry : 2
2022/05/03 07:02:12 : retry : 3
2022/05/03 07:02:12 : WiFi restart : error : 3
2022/05/03 07:03:04 : retry : 1
2022/05/03 07:04:04 : retry : 2
2022/05/03 07:05:07 : retry : 3

途中省略　restart　4～8

2022/05/03 07:20:09 : WiFi restart : error : 9
2022/05/03 07:21:06 : retry : 1
2022/05/03 07:22:03 : retry : 2
2022/05/03 07:23:00 : retry : 3
2022/05/03 07:23:00 : retry error -> reboot
2022/05/03 07:23:16 : WiFi restart : error : 10
2022/05/03 07:26:02 : 200
2022/05/03 07:27:01 : 200

Win10PCで、docker、docker composer インストールしてみました。
原因不明ですが「Attaching to atomcam_tools_builder_1」2時間程度、放置していましたがより先に進みませんでした。
![20220504-01](https://user-images.githubusercontent.com/933671/166858359-b8e3c49f-fd4d-4908-b4e6-ad57a8e79d3c.jpg)
インストールの手順は解ってきましたので、ubuntu linuxをPCにインストールして再度挑戦してみます。

**Comment by mnakada** [comment]
確認ありがとうございます。
WiFiが再接続できていないのが続いて再起動して繋がるという現象ですね。AtomCamのWiFiがifconfig down, upではうまく再接続できていないようで、ちょっと分からないですね。

shellでdocker-compose upを直接実行されていますが、./make.shを実行してください。
Dockerでのbuildはそんなに長時間固まる事はないので１〜２分動かない場合は何らかの原因で止まっています。

**Comment by kurokouji** [comment]
Win10 WSL2 Docker docker-composer、
Almalinux 8.5 Docker docker-composer
2つの環境で./make.sh を起動し、atomcam_tools.zip が生成されることを確認しました。

但し、こちらの生成ファイルを解凍し、microSDカードに書き込んでもAtomCam2起動しませんでした。
何か追加の設定が必要でしょうか、生成した　atomcam_tools.zip　をアップしたら参考になりますでしょうか。

**Comment by mnakada** [comment]
置いてください。みてみます。

**Comment by kurokouji** [comment]
ファイルが大きすぎると怒られてこちらには上げられなかったのでS3に上げました。
ご確認いただけましたら幸いです。
https://2022-atomcam-tools.s3.ap-northeast-1.amazonaws.com/20220507/linux_atomcam_tools.zip
https://2022-atomcam-tools.s3.ap-northeast-1.amazonaws.com/20220507/win_atomcam_tools.zip

**Comment by mnakada** [comment]
確認しました。
build-scriptで一部抜けがありました。
Ver.1.3.1で修正しました。

**Comment by kurokouji** [comment]
早速対応ありがとうございます。
ビルドしてみます。

**Comment by kurokouji** [comment]
動作状況次の通りです。
Win10 WSL2 Docker docker-composer：Cam起動しました、WebUI、sshとも正常動作。
Almalinux 8.5 Docker docker-composer：Cam起動しました、WebUI、sshとも動作しない。

Win10 WSL2はubuntuベースですので、
Ubuntu linuxで環境構築して確認してみます。

**Comment by kurokouji** [comment]
動作状況次の通りです。
Almalinux 8.5 Docker docker-composer：Cam起動しました、WebUI、sshとも正常動作。
atomcam_toolsが動かなかった原因はmicroSD 128GBのフォーマットでした。
「I-O_DATA_ハードディスクフォーマッタ」でFAT32にしたところ正常動作となりました。
こちらでもカスタム更新zipファイルが作成可能になりました、ありがとうございます。
