### ISSUE TITLE
RTSP and offical app live view

### ISSUE THREAD

**Issue by gtxaspec** [mnakada/atomcam_tools#21]
@mnakada,

I have observed when using the libcallback to hook iCamera for rtsp, that using the official app "ATOM" or  in my case, "wyze", the live-view feed does not work unless "360p" mode is selected, HD and SD mode does not produce any video.  Have you experienced this?

**Comment by mnakada** [comment]
In the case of AtomCam, HD and SD are output in 1080P and only the bandwidth is different.
Since libcallback specifies 1080P, HD and SD will pass, but if 360P is specified, it will not work.

Have you fixed the libcallback setting to 360P?
If you set the Wyze app to HD and the libcallback to 1920x1080P or modify it to accommodate the change in resolution, I think it will work.

**Comment by gtxaspec** [comment]
My mistake perhaps I didn't explain properly,  

360p works fine, it is 1080P which does **not** work, there is no video at all in the app.  Streaming via the rtsp server, the 1080p is fine there.  It just does not work in the app.

**Comment by mnakada** [comment]
On AtomCam, the app is able to switch between HD/SD/360P and display correctly.
The rtsp server is outputting correctly in 1080P for HD/SD, but when set to 360P it does not work properly.

Is there some kind of delay affecting this?

**Comment by mnakada** [comment]
Is it possible that the video buffer specified in the boot option of the kernel is insufficient?
Please check the following document.
https://github.com/openmiko/openmiko/blob/master/doc/ram.md

AtomCam specifies the following mem and rmem in configs/kernel.config. I think this value is different from Waze.
```
CONFIG_CMDLINE="console=ttyS1,115200n8 mem=80M@0x0 rmem=48M@0x5000000 rdinit=/init mtdparts=jz_sfc:256K(boot),1984K(kernel),3904K(rootfs),3904K(app),1984K(kback),3904K(aback),384K(cfg),64K(para)"
```

**Comment by gtxaspec** [comment]
i will inspect this, thank you for the tip!

**Comment by gtxaspec** [comment]
it seems the differences between atom and wyze iCamera are substantial, I am unable to get libcallback working without further extensive modification.  Perhaps the key is to enable ch2 of the isp, according to the ingenic t31 SDK.
