### ISSUE TITLE
iPadのsafari、chromeで設定ボタンが表示されません

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#22]
atomcam_toolsをiPadで利用したところWebUIで「設定ボタン」が表示されませんでした。
![win10_edge](https://user-images.githubusercontent.com/933671/165763503-91792eb1-dae9-4ef6-92c6-96016938cf22.jpg)
Win10のedge　右下に「設定」が表示されています。

![firefox](https://user-images.githubusercontent.com/933671/165763789-976248df-6b00-4886-8d6d-e6722526f762.jpg)
iPadのfirefox　「設定」が表示されません

![chrome](https://user-images.githubusercontent.com/933671/165764026-dfd4ca3c-ccc0-4cac-b75e-3645c6414469.jpg)
iPadのchrome　「設定」が表示されません
画面コピーをアップロードします、ご確認の程、よろしくお願いします。

**Comment by kurokouji** [comment]
android　もチェックしてみました。
![note8-Firefox](https://user-images.githubusercontent.com/933671/166086896-722f54b2-593d-4a0b-a538-3b63a25fceb1.jpg)
Firefox　(android　Galaxy　Note8)「設定」が表示されません

![note8-Chrome](https://user-images.githubusercontent.com/933671/166086898-9751642f-838c-44c4-8ecf-cac0673b5580.jpg)
Chrome　(android　Galaxy　Note8)「設定」が表示されません
参考まで。

**Comment by mnakada** [comment]
Ver.1.2.22で修正しました。
iOSは確認しましたが、Androidは未確認です。

**Comment by kurokouji** [comment]
Ver.1.2.22確認しました。
iOS、Androidとも「設定」表示されています。
変更が「設定」ボタンにより反映することも確認しました。
スマホでの利用も完璧です、ありがとうございました。

通常
![Chrome01](https://user-images.githubusercontent.com/933671/166395226-23fe849c-8b74-4a60-9596-38f98747bf04.jpg)

画像拡大
![Chrome02](https://user-images.githubusercontent.com/933671/166395275-dd4d309f-58c5-4df3-8e3b-c870b47be490.jpg)

横向き
![Chrome03](https://user-images.githubusercontent.com/933671/166395304-4b949eaf-34f3-421a-afdc-5aef0a8d7631.jpg)
