### ISSUE TITLE
CAMのスピーカーから任意の音(wav)を出力する機能について

### ISSUE THREAD

**Issue by midori-mushi** [mnakada/atomcam_tools#23]
大変有用に利用させていただいています。

CAMのスピーカーから、事前に用意しておいた任意の音(wav)を出力する機能は無理でしょうか？
（wavファイルをCAMに流し込んでWebUIのボタン押下で音出力、など）

今でも純正アプリの機能で、スマホのマイクからCAMのスピーカーへの音声出力が可能ですが、PC/マイコンから任意のトリガーでWebUI(の操作を疑似的に）操作して、CAMからwavを出力したいです。

→具体的には、条件を満たすと「こんにちは」とCAMから事前に用意していた音声を出力。

あるいは筋違いかと思いますが、もし現状のままでも実現できるヒントを、何かご教授いただけると大変ありがたいです。alsamixerではloopbackしか検出されず、aplayでの再生も無音です。
toolsのソースを拝見し、cmd.cgiにwebhookするとwebcmd.shが実行する仕組みを理解（および動作を確認）しましたので、もしaplayで再生できるようになれば、webcmd.shを書き換えて自力でも出来そうに思います。
ご検討をお願いいたします。

**Comment by gtxaspec** [comment]
does this binary work for you, playing audio .wav via command line?

https://github.com/gtxaspec/wz_mini_hacks/blob/master/SD_ROOT/wz_mini/bin/audioplay_t31

**Comment by midori-mushi** [comment]
Hello.
Thank you for your suggestion.
I copied it from the client with scp, chmod 777 and ran it,
Did not work.

  -sh: /root/audioplay_t31: not found

The output of the "file command" 

  audioplay_t31: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-uClibc.so.0, stripped

**Comment by gtxaspec** [comment]
you may have to run this inside the atom chroot.

**Comment by midori-mushi** [comment]
Audioplay_t31 worked the way you taught me!
appreciate.
But unfortunately I get an error.

The wav file uses /wz_mini/usr/share/audio/init.wav.

/usr/sbin/audioplay_t31 /usr/sbin/init.wav 50
[INFO]        : Playing the audio /usr/sbin/init.wav file.
[INFO]        : Volume is set to 50.
Segmentation fault

**Comment by gtxaspec** [comment]
Ah, it seems it is incompatible for some reason.  Here are the sources:

https://github.com/BiatuAutMiahn/IVSP-T31-1.1.1-20200508/blob/main/software/sdk/Ingenic-SDK-T31-1.1.1-20200508/samples/libimp-samples/sample-Ao.c

**Comment by gtxaspec** [comment]
it appears there is a problem, audioplay_t31 works when the audio.ko driver is loaded, but before iCamera is loaded.  It seems that iCamera is blocking the audio app from working.

**Comment by midori-mushi** [comment]
早速のご対応ありがとうございます。
shellおよびWebAPIでの実行ができました！
wavファイルは/atomの下に置いて、path指定/atom以下を指定するのですね

WebAPIについても機能実装ありがとうございます。
toolsのVerUPのたびにwebcmd.shを書き換える覚悟でいましたので助かります。
大変感謝いたします。

**Comment by mnakada** [comment]
SD-Card上にwaveFileを置いておけばupdateでも消えないです。
/media/mmc/hoge.wavでアクセスできます。
transcodeしていないので16bit/mono/PCM/8KHz以外のフォーマットはエラーになります。

**Comment by midori-mushi** [comment]
/media/mmc/　試しました。こちらに置くと便利ですね。
wavフォーマットも了解しました。stereoや8KHz以外だとERRORになることを確認しました。

ありがとうございます。

**Comment by midori-mushi** [comment]
すいません。
今気づいたのですがwavファイルの最後１秒くらいが切れるように思います。

５秒、２秒のファイルを試しましたが、どちらも切れているようです。
サンプリングレートをツールで8KHzに変換しているので、その影響なのかもしれないのですが、
windowsでは変換前、変換後どちらも切れずに聞こえます。

https://www.hke.jp/products/voice/voice_audition.htm
https://note.cman.jp/other/voice/

こちらのファイルをSoundEngineFreeで8KHzにしています。

**Comment by mnakada** [comment]
変換後のファイルを置いてもらう事は可能ですか？
wave fileのフォーマットを簡易的にdecodeしているので、ファイルの構造が何か違う可能性があります。

それか、内部bufferと終了時の待ち時間の関係かもしれません。
bufferの吐き出しが完了してから停止処理するべきなのですが現状は固定で待って停止しています。
待ち時間が２秒なので、数秒のファイルだと起きないはずなのですが。
再生完了を待つ仕組みがあると思うので、ちょっとみてみます。

**Comment by midori-mushi** [comment]
[human.zip](https://github.com/mnakada/atomcam_tools/files/8644545/human.zip)
[01.femal.zip](https://github.com/mnakada/atomcam_tools/files/8644549/01.femal.zip)

ありがとうございます、こちらになります。
よろしくお願いいたします。

**Comment by mnakada** [comment]
Ver.1.3.1で修正しました。

**Comment by midori-mushi** [comment]
早速のご対応ありがとうございます。
自システムに組み込み、有用に動いています。
大変感謝いたします。
