### ISSUE TITLE
v1.3.0からv1.3.1でATOMアプリ音声がボリュームダウンしたようです。

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#25]
v1.3.1に更新したところ、ATOMアプリで、通常聞こえていた音がモニタできなくなっていました。
v1.3.0に戻したらいつものようにモニタ出来ました、確認お願いします。

**Comment by gtxaspec** [comment]
I experienced the same issue.  can not hear audio from camera or use microphone to talk to camera...the issue is the latest audio_play.c included with libcallback... I have reverted to using the previous version...

**Comment by mnakada** [comment]
確認してみます。

**Comment by mnakada** [comment]
Ver.1.3.2で修正しました。

**Comment by kurokouji** [comment]
Ver.1.3.2 更新ありがとうございます、音声回復いたしました。
また気づいた点ありましたらお知らせいたします。
