### ISSUE TITLE
set video_callback bitrate

### ISSUE THREAD

**Issue by gtxaspec** [mnakada/atomcam_tools#26]
@mnakada, are you familiar with a way to set the bitrate (kbps) for the video hooked by video_callback?   perhaps it could be adjusted in the source.

**Comment by mnakada** [comment]
I don't know.
But I think it is difficult because the values held by iCamera_app must be changed at the same time as the settings on the SDK side to be consistent.
I think you can change the values on the SDK side by calling the API, but on the iCamera_app side, you cannot get the reference address to the variables.

**Comment by gtxaspec** [comment]
ah, yes the api, I understand.  comparisons with the official rtsp (1000kbps avg) and the libcallback (200kpbs avg) the difference is remarkable.

**Comment by mnakada** [comment]
How do you measure that bitrate?
Can I check it?

**Comment by gtxaspec** [comment]
@mnakada i have discovered you can adjust the bitrate using:

```
        /system/bin/impdbg --enc_rc_s 0:48:4:2048
        /system/bin/impdbg --enc_rc_s 0:52:4:2048
```

the api can reset these changes, be aware.  

```impdbg --enc_info```
gives more info on what the other options are.

the first one is MAX BITRATE
the second is TARGET bitrate.

**Comment by thematrixdev** [comment]
Is the video bitrate mentioned here refers to the video saving to SD-card?
I wonder if the bitrate could be reduced so as to reduce IO load.

**Comment by gtxaspec** [comment]
i am not sure if it related to SD card, you should try it

**Comment by gtxaspec** [comment]
i just checked yes it does affect them.

**Comment by mnakada** [comment]
Thanks for the information.
I will check it.

**Comment by thematrixdev** [comment]
@gtxaspec Is it possible to make the audio better quality?
Most of the time I cannot hear the content of the conversation.

**Comment by gtxaspec** [comment]
@thematrixdev not sure, from what I have discovered, the debug tools only allow us to adjust some of the video parameters.  perhaps @mnakada has some further insight or knowledge from his experience.

**Comment by mnakada** [comment]
@gtxaspec
I tried changing various impdbg setting values and audio on/off, but I did not see any change in bitrate.
In the case of AtomCam, observing the stream bitrate in VLC Statistics, it is about 600 kb/s when the video is still and about 2500 kb/s when the video is moving in front of the camera.

@thematrixdev
Audio is 8K/mono so the sampling frequency is low, but it looks like the hardware is not picking up the sound properly.

**Comment by gtxaspec** [comment]
@mnakada i understand, perhaps there are differences between the atomcam and wyze.  Would you share the output of ``impdbg --enc_info``` ?

**Comment by gtxaspec** [comment]
@thematrixdev maybe it could be related to the noise suppression of the T31 SDK...  the documentation states:

<div class="memproto" style="font: bold 14px / 22px Roboto, sans-serif; border-top: 1px solid rgb(168, 184, 217); border-left: 1px solid rgb(168, 184, 217); border-right: 1px solid rgb(168, 184, 217); padding: 6px 0px; color: rgb(37, 53, 85); text-shadow: rgba(255, 255, 255, 0.9) 0px 1px 1px; background-image: url(&quot;nav_f.png&quot;); background-repeat: repeat-x; background-color: rgb(226, 232, 242); box-shadow: rgba(0, 0, 0, 0.15) 5px 5px 5px; border-top-right-radius: 4px; border-top-left-radius: 4px; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

int IMP_AI_EnableNs | ( | IMPAudioIOAttr * | attr ,
-- | -- | -- | --
  |   | int | mode
  | ) |   |  

</dd></dl><dl class="section remark" style="font: 400 14px / 22px Roboto, sans-serif; padding: 0px; margin-left: 0px;"><dt style="font-weight: bold;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Remark</font></font></dt><dd style="margin-bottom: 6px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The mode parameter of noise suppression indicates the level of noise suppression, ranging from [0 to 3]. The higher the level, the cleaner the noise suppression.</font></font></dd><dd style="margin-bottom: 6px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">However, the cleaner the noise suppression is, the more sound details will be lost, so there is a contradiction here, which needs to be</font></font></dd><dd style="margin-bottom: 6px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">balance when using it.</font></font></dd></dl><dl class="section attention" style="font: 400 14px / 22px Roboto, sans-serif; padding: 0px 0px 0px 3px; margin-left: -7px; border-left: 4px solid rgb(255, 0, 0); border-top-color: rgb(255, 0, 0); border-right-color: rgb(255, 0, 0); border-bottom-color: rgb(255, 0, 0);"><dt style="font-weight: bold;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Notice</font></font></dt><dd style="margin-bottom: 6px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Echo cancellation includes noise suppression, if echo cancellation is enabled, noise suppression is not required.</font></font></dd></dl></div>int IMP_AI_EnableNs	(	[IMPAudioIOAttr](https://github.com/mnakada/atomcam_tools/issues/struct_i_m_p_audio_i_o_attr.html) * 	attr ,
int 	mode 
)		
Enables noise suppression for the specified audio input.

parameter
[in]	attr	Audio properties that require noise suppression.
[in]	mode	Noise suppression levels 0 to 3, see Level_ns.
return value
0	success.
non-zero	fail.
Remark
The mode parameter of noise suppression indicates the level of noise suppression, ranging from [0 to 3]. The higher the level, the cleaner the noise suppression.
However, the cleaner the noise suppression is, the more sound details will be lost, so there is a contradiction here, which needs to be
balance when using it.
Notice
Echo cancellation includes noise suppression, if echo cancellation is enabled, noise suppression is not required.

**Comment by mnakada** [comment]
@gtxaspec The output of impdbg -enc_info is as follows.

```
GROUP 0
	CHANNEL 0    1920x 1080     START H264 tf:673530     df:387        encdur:33667364, encodingFrameCnt:673143,endencodeFrameCnt=673143,endrelaseFrameCnt=673143,Fps:20.01,Bitrate:459.52
-------------------------------------------------
ch->index = 0
chnAttr->encAttr->eProfile = 77(0x4d) offset:size = 0:4
chnAttr->encAttr->uLevel = 41(0x29) offset:size = 4:1
chnAttr->encAttr->uTier = 0(0x0) offset:size = 5:1
chnAttr->encAttr->uWidth = 1920(0x780) offset:size = 6:2
chnAttr->encAttr->uHeight = 1080(0x438) offset:size = 8:2
chnAttr->encAttr->ePicFormat = 392(0x188) offset:size = 12:4
chnAttr->encAttr->eEncOptions = 294952(0x48028) offset:size = 16:4
chnAttr->encAttr->eEncTools = 156(0x9c) offset:size = 20:4
chnAttr->rcAttr->rcMode = 8(0x8) offset:size = 44:4
chnAttr->rcAttr->CappedQuality->uTargetBitRate = 720(0x2d0) offset:size = 48:4
chnAttr->rcAttr->CappedQuality->uMaxBitRate = 960(0x3c0) offset:size = 52:4
chnAttr->rcAttr->CappedQuality->iInitialQP = -1(0xffffffff) offset:size = 56:2
chnAttr->rcAttr->CappedQuality->iMinQP = 23(0x17) offset:size = 58:2
chnAttr->rcAttr->CappedQuality->iMaxQP = 51(0x33) offset:size = 60:2
chnAttr->rcAttr->CappedQuality->iIPDelta = 3(0x3) offset:size = 62:2
chnAttr->rcAttr->CappedQuality->iPBDelta = 3(0x3) offset:size = 64:2
chnAttr->rcAttr->CappedQuality->eRcOptions = 1(0x1) offset:size = 68:4
chnAttr->rcAttr->CappedQuality->uMaxPictureSize = 1920(0x780) offset:size = 72:4
chnAttr->rcAttr->CappedQuality->uMaxPSNR = 48(0x30) offset:size = 76:2
chnAttr->rcAttr->outFrmRate->frmRateNum = 20(0x14) offset:size = 80:4
chnAttr->rcAttr->outFrmRate->frmRateDen = 1(0x1) offset:size = 84:4
chnAttr->gopAttr->uGopCtrlMode = 2(0x2) offset:size = 88:4
chnAttr->gopAttr->uGopLength = 20(0x14) offset:size = 92:2
chnAttr->gopAttr->uNumB = 0(0x0) offset:size = 94:1
chnAttr->gopAttr->uMaxSameSenceCnt = 1(0x1) offset:size = 96:4
chnAttr->gopAttr->bEnableLT = 0(0x0) offset:size = 100:1
chnAttr->gopAttr->uFreqLT = 0(0x0) offset:size = 104:4
chnAttr->gopAttr->bLTRC = 0(0x0) offset:size = 108:1
	CHANNEL 4    1920x 1080      STOP JPEG tf:6950       df:8          encdur:33649471, encodingFrameCnt:6942,endencodeFrameCnt=6942,endrelaseFrameCnt=6942,Fps:0.50,Bitrate:235.95
-------------------------------------------------
ch->index = 4
chnAttr->encAttr->eProfile = 67108864(0x4000000) offset:size = 0:4
chnAttr->encAttr->uLevel = 0(0x0) offset:size = 4:1
chnAttr->encAttr->uTier = 0(0x0) offset:size = 5:1
chnAttr->encAttr->uWidth = 1920(0x780) offset:size = 6:2
chnAttr->encAttr->uHeight = 1080(0x438) offset:size = 8:2
chnAttr->encAttr->ePicFormat = 392(0x188) offset:size = 12:4
chnAttr->encAttr->eEncOptions = 294952(0x48028) offset:size = 16:4
chnAttr->encAttr->eEncTools = 156(0x9c) offset:size = 20:4
chnAttr->rcAttr->rcMode = 0(0x0) offset:size = 44:4
chnAttr->rcAttr->FixQP->iInitialQP = 32(0x20) offset:size = 48:2
chnAttr->rcAttr->outFrmRate->frmRateNum = 20(0x14) offset:size = 80:4
chnAttr->rcAttr->outFrmRate->frmRateDen = 1(0x1) offset:size = 84:4
chnAttr->gopAttr->uGopCtrlMode = 2(0x2) offset:size = 88:4
chnAttr->gopAttr->uGopLength = 40(0x28) offset:size = 92:2
chnAttr->gopAttr->uNumB = 0(0x0) offset:size = 94:1
chnAttr->gopAttr->uMaxSameSenceCnt = 1(0x1) offset:size = 96:4
chnAttr->gopAttr->bEnableLT = 0(0x0) offset:size = 100:1
chnAttr->gopAttr->uFreqLT = 0(0x0) offset:size = 104:4
chnAttr->gopAttr->bLTRC = 0(0x0) offset:size = 108:1
	CHANNEL 2    1920x 1080     START H265 tf:673530     df:124        encdur:33667365, encodingFrameCnt:673406,endencodeFrameCnt=673405,endrelaseFrameCnt=673405,Fps:20.01,Bitrate:70.39
-------------------------------------------------
ch->index = 2
chnAttr->encAttr->eProfile = 16777217(0x1000001) offset:size = 0:4
chnAttr->encAttr->uLevel = 50(0x32) offset:size = 4:1
chnAttr->encAttr->uTier = 1(0x1) offset:size = 5:1
chnAttr->encAttr->uWidth = 1920(0x780) offset:size = 6:2
chnAttr->encAttr->uHeight = 1080(0x438) offset:size = 8:2
chnAttr->encAttr->ePicFormat = 392(0x188) offset:size = 12:4
chnAttr->encAttr->eEncOptions = 294952(0x48028) offset:size = 16:4
chnAttr->encAttr->eEncTools = 156(0x9c) offset:size = 20:4
chnAttr->rcAttr->rcMode = 8(0x8) offset:size = 44:4
chnAttr->rcAttr->CappedQuality->uTargetBitRate = 600(0x258) offset:size = 48:4
chnAttr->rcAttr->CappedQuality->uMaxBitRate = 800(0x320) offset:size = 52:4
chnAttr->rcAttr->CappedQuality->iInitialQP = -1(0xffffffff) offset:size = 56:2
chnAttr->rcAttr->CappedQuality->iMinQP = 32(0x20) offset:size = 58:2
chnAttr->rcAttr->CappedQuality->iMaxQP = 51(0x33) offset:size = 60:2
chnAttr->rcAttr->CappedQuality->iIPDelta = -1(0xffffffff) offset:size = 62:2
chnAttr->rcAttr->CappedQuality->iPBDelta = -1(0xffffffff) offset:size = 64:2
chnAttr->rcAttr->CappedQuality->eRcOptions = 1(0x1) offset:size = 68:4
chnAttr->rcAttr->CappedQuality->uMaxPictureSize = 1920(0x780) offset:size = 72:4
chnAttr->rcAttr->CappedQuality->uMaxPSNR = 48(0x30) offset:size = 76:2
chnAttr->rcAttr->outFrmRate->frmRateNum = 20(0x14) offset:size = 80:4
chnAttr->rcAttr->outFrmRate->frmRateDen = 1(0x1) offset:size = 84:4
chnAttr->gopAttr->uGopCtrlMode = 2(0x2) offset:size = 88:4
chnAttr->gopAttr->uGopLength = 40(0x28) offset:size = 92:2
chnAttr->gopAttr->uNumB = 0(0x0) offset:size = 94:1
chnAttr->gopAttr->uMaxSameSenceCnt = 1(0x1) offset:size = 96:4
chnAttr->gopAttr->bEnableLT = 0(0x0) offset:size = 100:1
chnAttr->gopAttr->uFreqLT = 0(0x0) offset:size = 104:4
chnAttr->gopAttr->bLTRC = 0(0x0) offset:size = 108:1
GROUP 1
	CHANNEL 1     640x  360     START H265 tf:673541     df:112        encdur:33667365, encodingFrameCnt:673429,endencodeFrameCnt=673429,endrelaseFrameCnt=673429,Fps:20.01,Bitrate:95.16
-------------------------------------------------
ch->index = 1
chnAttr->encAttr->eProfile = 16777217(0x1000001) offset:size = 0:4
chnAttr->encAttr->uLevel = 50(0x32) offset:size = 4:1
chnAttr->encAttr->uTier = 1(0x1) offset:size = 5:1
chnAttr->encAttr->uWidth = 640(0x280) offset:size = 6:2
chnAttr->encAttr->uHeight = 360(0x168) offset:size = 8:2
chnAttr->encAttr->ePicFormat = 392(0x188) offset:size = 12:4
chnAttr->encAttr->eEncOptions = 294952(0x48028) offset:size = 16:4
chnAttr->encAttr->eEncTools = 156(0x9c) offset:size = 20:4
chnAttr->rcAttr->rcMode = 8(0x8) offset:size = 44:4
chnAttr->rcAttr->CappedQuality->uTargetBitRate = 135(0x87) offset:size = 48:4
chnAttr->rcAttr->CappedQuality->uMaxBitRate = 180(0xb4) offset:size = 52:4
chnAttr->rcAttr->CappedQuality->iInitialQP = -1(0xffffffff) offset:size = 56:2
chnAttr->rcAttr->CappedQuality->iMinQP = 23(0x17) offset:size = 58:2
chnAttr->rcAttr->CappedQuality->iMaxQP = 51(0x33) offset:size = 60:2
chnAttr->rcAttr->CappedQuality->iIPDelta = -1(0xffffffff) offset:size = 62:2
chnAttr->rcAttr->CappedQuality->iPBDelta = -1(0xffffffff) offset:size = 64:2
chnAttr->rcAttr->CappedQuality->eRcOptions = 1(0x1) offset:size = 68:4
chnAttr->rcAttr->CappedQuality->uMaxPictureSize = 640(0x280) offset:size = 72:4
chnAttr->rcAttr->CappedQuality->uMaxPSNR = 48(0x30) offset:size = 76:2
chnAttr->rcAttr->outFrmRate->frmRateNum = 20(0x14) offset:size = 80:4
chnAttr->rcAttr->outFrmRate->frmRateDen = 1(0x1) offset:size = 84:4
chnAttr->gopAttr->uGopCtrlMode = 2(0x2) offset:size = 88:4
chnAttr->gopAttr->uGopLength = 20(0x14) offset:size = 92:2
chnAttr->gopAttr->uNumB = 0(0x0) offset:size = 94:1
chnAttr->gopAttr->uMaxSameSenceCnt = 1(0x1) offset:size = 96:4
chnAttr->gopAttr->bEnableLT = 0(0x0) offset:size = 100:1
chnAttr->gopAttr->uFreqLT = 0(0x0) offset:size = 104:4
chnAttr->gopAttr->bLTRC = 0(0x0) offset:size = 108:1
	CHANNEL 5     640x  360      STOP JPEG tf:19         df:4          encdur:33235296, encodingFrameCnt:15,endencodeFrameCnt=15,endrelaseFrameCnt=15,Fps:0.00,Bitrate:0.20
-------------------------------------------------
ch->index = 5
chnAttr->encAttr->eProfile = 67108864(0x4000000) offset:size = 0:4
chnAttr->encAttr->uLevel = 0(0x0) offset:size = 4:1
chnAttr->encAttr->uTier = 0(0x0) offset:size = 5:1
chnAttr->encAttr->uWidth = 640(0x280) offset:size = 6:2
chnAttr->encAttr->uHeight = 360(0x168) offset:size = 8:2
chnAttr->encAttr->ePicFormat = 392(0x188) offset:size = 12:4
chnAttr->encAttr->eEncOptions = 294952(0x48028) offset:size = 16:4
chnAttr->encAttr->eEncTools = 156(0x9c) offset:size = 20:4
chnAttr->rcAttr->rcMode = 0(0x0) offset:size = 44:4
chnAttr->rcAttr->FixQP->iInitialQP = 32(0x20) offset:size = 48:2
chnAttr->rcAttr->outFrmRate->frmRateNum = 20(0x14) offset:size = 80:4
chnAttr->rcAttr->outFrmRate->frmRateDen = 1(0x1) offset:size = 84:4
chnAttr->gopAttr->uGopCtrlMode = 2(0x2) offset:size = 88:4
chnAttr->gopAttr->uGopLength = 40(0x28) offset:size = 92:2
chnAttr->gopAttr->uNumB = 0(0x0) offset:size = 94:1
chnAttr->gopAttr->uMaxSameSenceCnt = 1(0x1) offset:size = 96:4
chnAttr->gopAttr->bEnableLT = 0(0x0) offset:size = 100:1
chnAttr->gopAttr->uFreqLT = 0(0x0) offset:size = 104:4
chnAttr->gopAttr->bLTRC = 0(0x0) offset:size = 108:1
```

**Comment by gtxaspec** [comment]
ah, i can see the default settings are simliar:

AtomCam:
```
chnAttr->rcAttr->rcMode = 8(0x8) offset:size = 44:4
chnAttr->rcAttr->CappedQuality->uTargetBitRate = 720(0x2d0) offset:size = 48:4
chnAttr->rcAttr->CappedQuality->uMaxBitRate = 960(0x3c0) offset:size = 52
```
Wyze:

```
chnAttr->rcAttr->rcMode = 8(0x8) offset:size = 44:4
chnAttr->rcAttr->CappedQuality->uTargetBitRate = 720(0x2d0) offset:size = 48:4
chnAttr->rcAttr->CappedQuality->uMaxBitRate = 960(0x3c0) offset:size = 52:4
```

running the following increases quality from the rtsp stream significantly for:

```
/system/bin/impdbg --enc_rc_s 0:44:4:2
/system/bin/impdbg --enc_rc_s 0:48:4:4096
/system/bin/impdbg --enc_rc_s 0:52:4:4096
```
you can run `impdbg` after you run the commands to verify they have been applied properly.  Does this work with ATOM?

**Comment by mnakada** [comment]
The setting values have changed, but the RTSP bitrate is still the same.
The image quality does not appear to have changed either.
```
chnAttr->rcAttr->rcMode = 2(0x2) offset:size = 44:4
chnAttr->rcAttr->Vbr->uTargetBitRate = 4096(0x1000) offset:size = 48:4
chnAttr->rcAttr->Vbr->uMaxBitRate = 4096(0x1000) offset:size = 52:4
```
Maybe AtomCam has some other setting.

**Comment by gtxaspec** [comment]
closing pending more research!
