### ISSUE TITLE
イベント通知について

### ISSUE THREAD

**Issue by izumino-chino** [mnakada/atomcam_tools#32]
Ver.1.3.6（それ以前は、未確認です）
・type: uploadVideoFinish
・mime:video/mp4
が発生していないように思います。

お手数ですが、ご確認頂けますでしょうか？

**Comment by gtxaspec** [comment]
can confirm, events that are due to be uploaded to the cloud do not work. 
could it be that the helper programs expect the path of /tmp for the recordings?

**Comment by mnakada** [comment]
すみません。
見落としてました。
修正してupdateします。

**Comment by mnakada** [comment]
Ver.1.3.7で修正しました。

**Comment by izumino-chino** [comment]
Ver.1.3.7で修正されていることを確認できました。
ありがとうございます。

**Comment by mnakada** [comment]
確認ありがとうございます。
