### ISSUE TITLE
Ubuntu on Windows、AlmaLinuxで　make.sh　がエラーで止まります。

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#33]
久しぶりに動作確認しました、git pull して　./make.sh
何か追加の設定が必要でしょうか、お気づきの点ありましたらご教授ください。

Ubuntu on Windows
$ git log -n 1
commit 868fa97719c98f7d9b8e9ef8b5f61a0b0b164ca3 (HEAD -> main, tag: Ver.1.3.7, origin/main, origin/HEAD)
Author: Mitsuru Nakada
Date: Sat May 21 00:27:06 2022 +0900

Ver.1.3.7
$ ./make.sh
docker-compose ps | grep builder || docker-compose up -d
atomcam_tools_builder_1 tail -f /dev/null Exit 255
docker-compose exec builder /src/buildscripts/build_all | tee rebuild_date +"%Y%m%d_%H%M%S".log
ERROR: No container found for builder_1
centos@DESKTOP-T4IL0LP:~/atomcam_tools$

AlmaLinux
[root@localhost atomcam_tools]# git log -n 1
commit 868fa97719c98f7d9b8e9ef8b5f61a0b0b164ca3 (HEAD -> main, tag: Ver.1.3.7, origin/main, origin/HEAD)
Author: Mitsuru Nakada
Date: Sat May 21 00:27:06 2022 +0900

Ver.1.3.7
[root@localhost atomcam_tools]# ./make.sh
docker-compose ps | grep builder || docker-compose up -d
atomcam_tools_builder_1 tail -f /dev/null Exit 137
docker-compose exec builder /src/buildscripts/build_all | tee rebuild_date +"%Y%m%d_%H%M%S".log
[root@localhost atomcam_tools]#

**Comment by mnakada** [comment]
Makefileしゅうせいしました
次回updateで入ります

**Comment by kurokouji** [comment]
いつもありがとうございます。
Ver.1.3.8　でビルドしてみました、次のメッセージで先へ進みません。
何か設定が必要でしょうか。
almakinux
atomcam_tools_builder_1   tail -f /dev/null   Exit 137        

Ubuntu on Windows
atomcam_tools_builder_1   tail -f /dev/null   Exit 255


almalinux

[root@localhost atomcam_tools]# git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 75 (delta 52), reused 72 (delta 49), pack-reused 0
Unpacking objects: 100% (75/75), 12.04 KiB | 560.00 KiB/s, done.
From https://github.com/mnakada/atomcam_tools
   f32e4e6..aa8eacf  main            -> origin/main
 * [new branch]      audio-debug     -> origin/audio-debug
 * [new branch]      libcallback-log -> origin/libcallback-log
 * [new branch]      network-setup   -> origin/network-setup
 * [new tag]         Ver.1.3.8       -> Ver.1.3.8
Updating f32e4e6..aa8eacf
Fast-forward
 Makefile                                               |   1 +
 buildscripts/build_all                                 |   5 +++
 buildscripts/local_build.sh                            |   5 +++
 configs/atomcam_defconfig                              |  13 +++++++-
 configs/atomhack.ver                                   |   2 +-
 configs/kernel.config                                  |  26 +++++++++++++--
 libcallback/audio_callback.c                           |  32 +++++++++---------
 libcallback/audio_play.c                               |   3 +-
 libcallback/command.c                                  |   2 ++
 libcallback/curl.c                                     |  38 ++++++++++++++++------
 libcallback/opendir.c                                  |   2 +-
 libcallback/remove.c                                   |   2 +-
 libcallback/video_callback.c                           |   4 +--
 lima-docker.yml                                        |  70 +++++++++++++++++++++++++++++++++++++++
 overlay_rootfs/etc/init.d/{S37fwupdate => S32fwupdate} |   0
 overlay_rootfs/etc/init.d/S33hackini                   |   1 +
 overlay_rootfs/etc/init.d/S34mountfs                   |  65 +++++++++++++++++++++++++++++++++++++
 overlay_rootfs/etc/init.d/{S40network => S35network}   |   2 +-
 overlay_rootfs/etc/init.d/S35wifi                      |  21 ------------
 overlay_rootfs/etc/init.d/{S45ntpd => S36ntpd}         |  20 ++++--------
 overlay_rootfs/etc/init.d/{S50sshd => S37sshd}         |   0
 overlay_rootfs/etc/init.d/S38atomcam                   | 101 +++++++++++++++++++++++----------------------------------
 overlay_rootfs/etc/init.d/S58rtspserver                |   8 +----
 overlay_rootfs/scripts/atom_init.sh                    |  41 +----------------------
 overlay_rootfs/scripts/health_check.sh                 |   3 +-
 overlay_rootfs/scripts/killall.sh                      |   4 +++
 overlay_rootfs/scripts/lighttpd.sh                     |   2 ++
 overlay_rootfs/scripts/network_init.sh                 |  78 ++++++++++++++++++++++++++++++++++++++++++++
 overlay_rootfs/scripts/{boa.sh => null.sh}             |   0
 overlay_rootfs/scripts/wpa_cli.sh                      |   3 ++
 patches/tinyalsa/tinyalsa.patch                        |  20 ++++++++++--
 31 files changed, 391 insertions(+), 183 deletions(-)
 create mode 100644 lima-docker.yml
 rename overlay_rootfs/etc/init.d/{S37fwupdate => S32fwupdate} (100%)
 create mode 100755 overlay_rootfs/etc/init.d/S34mountfs
 rename overlay_rootfs/etc/init.d/{S40network => S35network} (86%)
 delete mode 100755 overlay_rootfs/etc/init.d/S35wifi
 rename overlay_rootfs/etc/init.d/{S45ntpd => S36ntpd} (50%)
 rename overlay_rootfs/etc/init.d/{S50sshd => S37sshd} (100%)
 create mode 100755 overlay_rootfs/scripts/killall.sh
 create mode 100755 overlay_rootfs/scripts/network_init.sh
 rename overlay_rootfs/scripts/{boa.sh => null.sh} (100%)
 create mode 100755 overlay_rootfs/scripts/wpa_cli.sh
[root@localhost atomcam_tools]# ./make.sh 
docker-compose ps | grep -v exited | grep builder || docker-compose up -d
atomcam_tools_builder_1   tail -f /dev/null   Exit 137        
docker-compose exec builder /src/buildscripts/build_all | tee rebuild_`date +"%Y%m%d_%H%M%S"`.log
[root@localhost atomcam_tools]# 

Ubuntu on Windows

centos@DESKTOP-T4IL0LP:~/atomcam_tools$ git pull
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 78 (delta 54), reused 72 (delta 49), pack-reused 0
Unpacking objects: 100% (78/78), 12.78 KiB | 304.00 KiB/s, done.
From https://github.com/mnakada/atomcam_tools
   868fa97..aa8eacf  main            -> origin/main
 * [new branch]      33-ubuntu-on-windowsalmalinuxで　makesh　がエラーで止まります -> origin/33-ubuntu-on-windowsalmalinuxで　makesh　がエラーで止まります
 * [new branch]      audio-debug     -> origin/audio-debug
 * [new branch]      libcallback-log -> origin/libcallback-log
 * [new branch]      network-setup   -> origin/network-setup
 * [new tag]         Ver.1.3.8       -> Ver.1.3.8
Updating 868fa97..aa8eacf
Fast-forward
 Makefile                                               |   3 +-
 buildscripts/build_all                                 |   5 +++
 buildscripts/local_build.sh                            |   5 +++
 configs/atomcam_defconfig                              |  13 +++++++-
 configs/atomhack.ver                                   |   2 +-
 configs/kernel.config                                  |  26 +++++++++++++--
 libcallback/audio_callback.c                           |  32 +++++++++---------
 libcallback/audio_play.c                               |   3 +-
 libcallback/command.c                                  |   2 ++
 libcallback/curl.c                                     |  38 ++++++++++++++++------
 libcallback/opendir.c                                  |   2 +-
 libcallback/remove.c                                   |   2 +-
 libcallback/video_callback.c                           |   4 +--
 lima-docker.yml                                        |  70 +++++++++++++++++++++++++++++++++++++++
 overlay_rootfs/etc/init.d/{S37fwupdate => S32fwupdate} |   0
 overlay_rootfs/etc/init.d/S33hackini                   |   1 +
 overlay_rootfs/etc/init.d/S34mountfs                   |  65 +++++++++++++++++++++++++++++++++++++
 overlay_rootfs/etc/init.d/{S40network => S35network}   |   2 +-
 overlay_rootfs/etc/init.d/S35wifi                      |  21 ------------
 overlay_rootfs/etc/init.d/{S45ntpd => S36ntpd}         |  20 ++++--------
 overlay_rootfs/etc/init.d/{S50sshd => S37sshd}         |   0
 overlay_rootfs/etc/init.d/S38atomcam                   | 101 +++++++++++++++++++++++----------------------------------
 overlay_rootfs/etc/init.d/S58rtspserver                |   8 +----
 overlay_rootfs/scripts/atom_init.sh                    |  41 +----------------------
 overlay_rootfs/scripts/health_check.sh                 |   3 +-
 overlay_rootfs/scripts/killall.sh                      |   4 +++
 overlay_rootfs/scripts/lighttpd.sh                     |   2 ++
 overlay_rootfs/scripts/network_init.sh                 |  78 ++++++++++++++++++++++++++++++++++++++++++++
 overlay_rootfs/scripts/{boa.sh => null.sh}             |   0
 overlay_rootfs/scripts/wpa_cli.sh                      |   3 ++
 patches/tinyalsa/tinyalsa.patch                        |  20 ++++++++++--
 31 files changed, 392 insertions(+), 184 deletions(-)
 create mode 100644 lima-docker.yml
 rename overlay_rootfs/etc/init.d/{S37fwupdate => S32fwupdate} (100%)
 create mode 100755 overlay_rootfs/etc/init.d/S34mountfs
 rename overlay_rootfs/etc/init.d/{S40network => S35network} (86%)
 delete mode 100755 overlay_rootfs/etc/init.d/S35wifi
 rename overlay_rootfs/etc/init.d/{S45ntpd => S36ntpd} (50%)
 rename overlay_rootfs/etc/init.d/{S50sshd => S37sshd} (100%)
 create mode 100755 overlay_rootfs/scripts/killall.sh
 create mode 100755 overlay_rootfs/scripts/network_init.sh
 rename overlay_rootfs/scripts/{boa.sh => null.sh} (100%)
 create mode 100755 overlay_rootfs/scripts/wpa_cli.sh
centos@DESKTOP-T4IL0LP:~/atomcam_tools$



centos@DESKTOP-T4IL0LP:~/atomcam_tools$ ./make.sh
docker-compose ps | grep -v exited | grep builder || docker-compose up -d
atomcam_tools_builder_1   tail -f /dev/null   Exit 255
docker-compose exec builder /src/buildscripts/build_all | tee rebuild_`date +"%Y%m%d_%H%M%S"`.log
ERROR: No container found for builder_1
centos@DESKTOP-T4IL0LP:~/atomcam_tools$

**Comment by mnakada** [comment]
@kurokouji , Docker自体が起動してないように見えます。
最初にDockerを起動してから実行してください。

**Comment by kurokouji** [comment]
お手数かけます、Docker is running　は確認しました。
![20220608-01](https://user-images.githubusercontent.com/933671/171768199-f6a8ff7d-b56e-401b-b300-8e9d95f069e7.jpg)

**Comment by mnakada** [comment]
docker-compose ps
の出力を送ってもらえますか？

**Comment by kurokouji** [comment]
コンソールハードコピー送ります。
![20220608-02](https://user-images.githubusercontent.com/933671/171769244-2ee17b96-430d-45b1-b64d-7ad405c29521.jpg)

**Comment by mnakada** [comment]
docker-compose psのstatusの表示が環境によって違うみたいですね。
取り敢えず
docker-compose up -d
でコンテナを起動してから再度makeして下さい。
後で対応検討します。

**Comment by kurokouji** [comment]
>docker-compose up -d
>でコンテナを起動してから再度makeして下さい。

ビルド成功しました。
update フォルダへ送信、reboot　で更新、動作確認しました。

**Comment by accept** [comment]
@kurokouji 
今更ですが、私も同じエラーが出まして、docker-composeの出力の違いだと思い、Makefile内のスクリプトを下記に修正していました。
その都度docker-compose up -dで立ち上げれば問題はないのでわざわざ直す必要もないかとは思いますが、参考になりましたら幸いです。
`docker-compose ps | grep -v Exit | grep builder || docker-compose up -d`

**Comment by kurokouji** [comment]
@accept, Makefile修正事項、お知らせいただきありがとうございます。
AlmaLinuxはビルドしてしまったので、Ubuntu on Windowsで試してみます。
本質を理解しないままbusyboxやらDockerを利用しておりますので些細なことで引っ掛かり皆さんのお手を煩わせすみません。

**Comment by kurokouji** [comment]
@accept,　Ubuntu on WindowsのMakefile内のスクリプトを
grep -v exited　から
grep -v Exit　に修正したところ問題なく「./make.sh」でビルドできました。

**Comment by mnakada** [comment]
Ver.1.3.9で修正しました。

**Comment by kurokouji** [comment]
修正ありがとうございます、AlmaLinux、Ubuntu on Windowsどちらもビルド完了しました。
不具合があるようでしたらまたお知らせいたします。

**Comment by kurokouji** [comment]
Ver.1.4.1 次のエラーで停止します、エラー画面送ります。
![20220623-01](https://user-images.githubusercontent.com/933671/175227008-47ce0ef0-b13b-4e2a-8a4b-396c0f9004c5.jpg)

**Comment by kurokouji** [comment]
Ver.1.4.3修正ありがとうございます、AlmaLinux、Ubuntu on Windowsどちらも次の手順でビルド完了しました。
AC2にてSD書込みからのインストール動作も確認しました。
＃ git pull
＃ docker-compose up -d
＃ make

***** 不具合報告 *****
ACS　にて動作が不安定になったような感じがします。ACSは手持ち1台しかないので決定的な情報ではありません。
UPDATEすると落ちる。SD書込みからのインストールで正常に起動しない。
何度かSD書込みからのインストールを行いatomcam_toolsの起動に成功することがある。
1晩経過したら、
ping応答なし、WebUI応答なし、ssh応答なし、sumbaへの録画は正常、iCamアプリでカメラoff
のような状況です。

AC2ではFAT32 128GBで運用しているものが数台有りますが不具合なくUPDATEできています。
ファームのバージョン違いによる挙動かと勘繰ったりしておりますが原因はわかりません。一応状況を報告します。

**Comment by kurokouji** [comment]
***** 不具合報告 続き *****
ACS　にてVer.1.4.1　に戻したところマイクロSD32GB、64GBで問題なく動作しております。

**Comment by hiroki-tagami** [comment]
詳しくは問題の切り分けができてないのですが、当方ではAtomCAM2で同じように1.4.3を適用後、
5,6時間程度の連続稼働でMOD機能だけ停止しているようです（通常のATOMCAMアプリからだと正常に動いているように見えますが、SSHやHTTPでのアクセスができません）

再起動すると一時的に復活はするのですが、どこかのタイミングでそのようになります。
当方の環境の問題かなと思ったのですが、1.4.1で治るならそれを試してみたいとおもいます。

**Comment by kurokouji** [comment]
@mnakada, @hiroki-tagami
AC2、ACSにてVer.1.4.5 動作確認しました。
動作不良の原因ですが連日の気温上昇によるカメラの誤動作のようです。
動作不良だった設置場所は2F東北向きの窓側、空気の流れ無しで気温は37.4度、電波の強度は-80dbmです。
ACSですが5mの延長コネクタで使用しています。
動作確認できた場所の気温は28.0度の室内環境、電波の強度は-49dbmです。
カメラのケースを触った間隔としては室内環境で「暖かい」感じ、
動作が不安定だった設置では触れないほどではないがかなり高温です。
電波の状態がよろしくないと送受信効率が悪くなり、動作温度も上昇すると思います。
カメラ内部のCPUや周辺回路の温度が取れれば比較の参考値になると思うのですが温度が読み取れる仕掛けが今のところありません。

「室内」で動いてるカメラを「窓際」に移動するとカメラが動作不良になり、「室内」に戻すと正常に動作しました。
但し、「動作不良」の状態から「正常動作」になる位置を調査しようと数回、「動作不良」で起動するとMicroSDの設定値が不定に書き換えられてしまうためか室内の環境の良い場所で起動しても、WebUI、SSHは正常に動作しなくなる場合があります。

@hiroki-tagami
状況が異なるかもしれませんが、参考にしてください。
AC2でも環境温度、電波強度による動作不良は同様に生じると思われます。
環境の良い状態で「Ver.1.4.5」の動作確認してみて下さい。

Wifi接続で有線LAN並みの良好な通信速度を得るためには-40～-30dbm程度電波強度が必要なようです。
当方が利用しているFS040Wではカメラ設置には短すぎる、2m程度の非常に狭い範囲です。
経験値による利用の目安としては-60dbmです。周囲のアクセスポイントとの輻輳・ノイズにより不安定な場合も考慮する必要があります。

**Comment by hiroki-tagami** [comment]
@kurokouji 
貴重な情報ありがとうございます。
今回事象が発生したのはテストのため室内に持ち込んでいた時だったのですが、
もともと野外でWiFiのつかみが最近悪くなったため熱を疑って室内に持ち込んでいました。

室内だったら熱暴走かどうかの切り分けができると思っていたのですが
熱のせいでMicroSD周りに不具合が出ていたとするならば、色々納得でき目からうろこでした。
引き続き色々問題の切り分けをしてみたいと思います。
