### ISSUE TITLE
USB-NCM機能

### ISSUE THREAD

**Issue by virmaior** [mnakada/atomcam_tools#38]
念の為に確認いたしますが、先のissueを見ると、現在のUSB-NCMの機能はないから、私の方で、作って、pull requestをすれば、@mnakada様はメインに入れることでしょうか。

Since you're also fluent in English, I can stick to that if you prefer.

**Comment by virmaior** [comment]
一応、https://github.com/mnakada/atomcam_tools/issues/27をベースにして、wz_miniのethernet over usbからbackportすると考えています。

**Comment by mnakada** [comment]
はい、pull requests歓迎します。
You may write in English :-)

**Comment by virmaior** [comment]
よろしくお願いします。
https://github.com/mnakada/atomcam_tools/pull/39

**Comment by mnakada** [comment]
margeしました。
