### ISSUE TITLE
atomcam_toolsを、microSD　64GB、128GB、256GB　に対応可能でしたらお願いします

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#4]
ATOM CAM 2、ATOM CAM SWINGで　atomcam_tools　を利用させていただいています。
もともとサポート対象外なのですが、32GBを超えるmicroSDも使用可能なようです。

microSDカードへの録画時間を延ばしたいためatomcam_tools　を128GBのmicroSDに書きこんで起動しましたが

ping応答はあります。
httpでは応答がありません
sshでは接続拒否されます。

32GBまではFAT32、それ以上はexFATのようです。

atomcam_toolsを、microSD　64GB、128GB、256GB　に対応可能でしたらお願いします。

**Comment by mnakada** [comment]
32GBを超えるSD-Cardへの対応はできないです。
理由は、linuxのkernel側はexFATに対応しているのですが、AtomCamのu-bootがexFATのメディアを認識できないためHackのイメージが認識されず、そのまま元のkernelイメージが起動してしまうためです。

**Comment by kurokouji** [comment]
>AtomCamのu-bootがexFATのメディアを認識できない

回答ありがとうございます、承知いたしました。128GBのmicroSDでの動作も納得できました。

**Comment by kurokouji** [comment]
追加報告です。
128GBのmicroSDカードで　atomcam_tools　の動作を確認いたしました。
FAT32を調査したところ、最大容量は2テラバイト、1ファイルの容量は最大4GBでした。

次のプログラム
I-O_DATA_ハードディスクフォーマッタ
https://www.iodata.jp/support/qanda/answer/s16470.htm

を使用し128GBのmicroSDをFAT32でフォーマットすることができました。
フォーマットしたmicroSDに　atomcam_tools　をインストールしたところ正常に、
webapp、sshともに利用することができました。
少なくとも1週間程度の連続録画記録が可能だと思われます。

Windows10でのフォーマットではOSの制限によりFAT32では32GBまでに制限さされており、それ以上はexFATとなるようです。
