### ISSUE TITLE
web server English version

### ISSUE THREAD

**Issue by virmaior** [mnakada/atomcam_tools#42]
I went ahead and translated the titles in the vue page into English (https://github.com/virmaior/atomcam_tools/commit/7346b2e180408737395bffee876572c022be47ea) but I'm not sure how best to contribute this to atomcam_tools.

This should be useful for any developers outside of Japan who are working on bringing similar functionality to wyze .

HTMLとJSは知っているけど、VUEは全然知らない. And looking at VUE's il8n method, it looks it would be more annoying than helpful to use since it would make it so every title and tooltip needs to be a variable for substitution.

**Comment by mnakada** [comment]
I had not thought about i18n because atomcam was for Japan only.
I will consider Vue-i18n.

**Comment by virmaior** [comment]
That looks pretty amazing. Do I need to build in docker to use a branch and test it?

**Comment by mnakada** [comment]
Clone the branch and execute the following to rewrite atomcam's web page.
```
cd atomcam_tools/web
npm i
./node_modules/.bin/webpack --mode development --progress
scp -p frontend/index.html frontend/bundle_* atomcam.local:/var/www

-> browser reload
```
If the language selector appears in the upper right corner, the page has been rewritten.
There are still some bugs related to the days of the week.

The language resources are in one file for ja and en, but it might be better to separate them.

**Comment by mnakada** [comment]
I have split the resource file.

**Comment by mnakada** [comment]
Corrections have been made except for the tooltip.
Please correct any strange expressions.
Please translate the tooltip if possible.

**Comment by virmaior** [comment]
resolved in current version and with @mnakada  修正漏れ fixes.
