### ISSUE TITLE
libcallback waitmotion

### ISSUE THREAD

**Issue by gtxaspec** [mnakada/atomcam_tools#46]
@mnakada 

In waitMotion.c,

what should be the proper behavior for "clear"?

should this only appear after motion detected,if not

why would clear appear before the timeout is reached?

example:

`cmd waitmotion 30` in a while loop

22/07/12-20:19:41 detect 197 229 202 263 - -
22/07/12-20:19:54 clear
22/07/12-20:19:59 clear
22/07/12-20:20:05 clear
22/07/12-20:20:12 clear
22/07/12-20:20:47 timeout
22/07/12-20:21:43 clear

**Comment by mnakada** [comment]
@gtxaspec ,
waitmotion hooks local_sdk_video_osd_update_rect, which draws a frame when motion detect in iCamera_app.

clear is output when the frame is cleared.
It can tell when motion detection is finished, but I'm not using it at the moment.

**Comment by gtxaspec** [comment]
thank you!
