### ISSUE TITLE
libcallback future

### ISSUE THREAD

**Issue by gtxaspec** [mnakada/atomcam_tools#48]
@mnakada the latest version of iCamera from wyze bundles in the liblocalsdk libraries.

see https://s3-us-west-2.amazonaws.com/wuv2/upgrade/WYZE_CAKP2JFUS/firmware/4.36.10.2163.tar

it appears they are aware of libcallback (hualai).

the atom system seems to use a slightly older version of the iCamera system, but it may catch up.  

Is there anyway to hook the functions when they are build in, without LDPRELOAD?

**Comment by mnakada** [comment]
It is static linked.
I have no idea.

We may have to build our app from the Ingenic SDK.
It will not be connected to the mobile app though.
