### ISSUE TITLE
dwc2 module kernel 

### ISSUE THREAD

**Issue by gtxaspec** [mnakada/atomcam_tools#49]
@mnakada,

I have a question, and seek your input.  Maybe you have some ideas, if you are familiar the usb host driver.

When I attempt to compile dwc2 as a kernel module (for atomcam2, but same issue with the wyze cam too), and then load it, nothing happens.  No output in dmesg, and nothing in lsusb.

It works just fine when compiled in to the kernel, obviously

very intriguing.

**Comment by mnakada** [comment]
I don't know.
I guess it's the timing of initialization that makes the difference.

**Comment by mnakada** [comment]
close this issue.
