### ISSUE TITLE
1.5.0にVersionUPしたらWebUIの文字が表示されなくなった

### ISSUE THREAD

**Issue by takeshi56** [mnakada/atomcam_tools#50]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/101503964/180146449-995ad9dd-a68f-4e48-aba8-bdd2990f91df.png">

Windows11 Chrome バージョン: 103.0.5060.114（Official Build） （64 ビット）

AC1/AC2/ACSwingいずれでも発生

と言う環境ですが、Javascriptの内容はこれから確認しようかと思っています。他に同じ症状の人はいませんでしょうか？
Configurationは反映されているように見えていまして、表示だけの問題だとすると文字コードとかの問題でしょうか？

**Comment by mnakada** [comment]
@takeshi56 ,　
すみませんが、ChromeのDevToolsのConsoleで
navigator.language
の出力結果を教えてもらえますか？

**Comment by takeshi56** [comment]
"ja-JP"となりました。

<img width="383" alt="image" src="https://user-images.githubusercontent.com/101503964/180167034-bd12c602-489d-419e-93e8-5111b39eb2d0.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/101503964/180167662-c864f1b8-bb39-45d3-ba99-ae8989439836.png">

他にもコンソールから何か得られないかと思いまして、叩いてみたものも共有します。

**Comment by mnakada** [comment]
タイトルバーの右端の上に言語選択があるのですが、一度Englishを選択後、日本語にもどして設定ボタンで保存してみてもらえますか。

**Comment by takeshi56** [comment]
治りました。ありがとうございます。

<img width="400" alt="image" src="https://user-images.githubusercontent.com/101503964/180211128-ec5929e7-e9e1-4aaf-abb4-78585e08f573.png">

**Comment by mnakada** [comment]
確認ありがとうございます。
次のupdateで初期値の設定方法を修正します。

**Comment by thematrixdev** [comment]
It seems to happen on 1.5.1 as well:
![image](https://user-images.githubusercontent.com/19472561/183235725-8bfc5a02-6b00-4be6-b745-5c899f69fc68.png)

**Comment by mnakada** [comment]
It is fixed in Ver.1.5.2.
