### ISSUE TITLE
javascript fails to run

### ISSUE THREAD

**Issue by thematrixdev** [mnakada/atomcam_tools#51]
I have just tried to run the web interface via Internet (with a domain name).

It is warned that:
![image](https://user-images.githubusercontent.com/19472561/180966282-a2ebfa71-7b94-4385-aabb-20756f298ba1.png)

It seems the MIME type is causing the error:
![image](https://user-images.githubusercontent.com/19472561/180966022-d8a548cd-1bd8-4ffe-8b06-479379aef4c2.png)

Thanks.

**Comment by mnakada** [comment]
I fixed it in Ver.1.5.3

**Comment by thematrixdev** [comment]
It works now. Thanks a lot!
