### ISSUE TITLE
180度反転とパンチルト

### ISSUE THREAD

**Issue by hiroshi3500** [mnakada/atomcam_tools#52]
Swingを天井から吊り下げで使っています。
純正アプリ内の設定で180度反転をしているとatomcam_toolsのパンとチルトの方向が感覚とズレてしまいます
純正アプリでパンチルトするよりtoolsの方が操作性も良いので180度反転しているときにはスライドを逆にするオプションは付けられないでしょうか？

**Comment by mnakada** [comment]
Ver.1.5.2で対応しました。
反転時は操作方向を逆にしています。

**Comment by mnakada** [comment]
Ver.1.5.3で起動時の方向がおかしくなる現象を修正しました。

**Comment by hiroshi3500** [comment]
対応ありがとうございます。とても快適です
