### ISSUE TITLE
use basic authentication instead of digest

### ISSUE THREAD

**Issue by thematrixdev** [mnakada/atomcam_tools#56]
I am trying to CURL on Home Assistant to control the cameras.
HTTP Digest Authentication is not supported.
https://www.home-assistant.io/integrations/rest_command/

As far as I understand, basic auth is sent in plain text, while digest is sent in hash.
Digest type is indeed more secure.
However, I believe most use case would be in LAN.
Even it is used via Internet, HTTPS is widely used nowadays.
Credentials sent in basic auth is encrypted in HTTPS.

May I suggest to switch to basic auth, for easy integration?

Thank you very much.

**Comment by mnakada** [comment]
If the access is within a LAN, wouldn't there be a need for password authentication?
In the case of BASIC authentication over http, I don't think there is any point in password authentication since the raw password is visible.

**Comment by thematrixdev** [comment]
No problem. I have found a workaround. Thanks.
