### ISSUE TITLE
RTSP secondary channel

### ISSUE THREAD

**Issue by thematrixdev** [mnakada/atomcam_tools#58]
Hello there.

Recently I am playing with Frigate and Double-Take.

Frigate suggest using 5 FPS for AI object detection, to preserve CPU workload.

Is it possible to stream H264 5FPS via secondary channel?

Thanks.

**Comment by mnakada** [comment]
Camera_app's video encoder has three outputs: 
#0 is 1080P-AVC, #1 is 360P-HEVC, and #3 is 1080P-HEVC.
Atomcam_tools switches #0,#3 to RTSP-main and #1 to RTSP-sub.
These are used for mobile apps, cloud, etc., so it is difficult to change the settings.
Is it possible to use the RTSP-main stream?

**Comment by thematrixdev** [comment]
I see. I will use the main stream. Thank you very much.
