### ISSUE TITLE
設定の曜日のズレ

### ISSUE THREAD

**Issue by hagsh** [mnakada/atomcam_tools#59]
・timelapse録画
・定期リスタート
ともに設定した曜日が設定の度にずれていきます。（土→金→木）
曜日の並びも日曜先頭のほうがありがたいです。
よろしくお願いいたします。

**Comment by mnakada** [comment]
指摘ありがとうございます。
ずれていく問題はVer.1.5.6で修正しました。
曜日の並びは人によって要求が違うので対応しません。

**Comment by hagsh** [comment]
確認できました。
ありがとうございます。
素晴らしい機能の公開提供に敬服いたしております。
