### ISSUE TITLE
swapファイルがないと起動しない at AtomCam2 

### ISSUE THREAD

**Issue by akirayou** [mnakada/atomcam_tools#6]
ReleaseにあったzipをSDカードにインストールしても、再起動を繰り返しました。
適当に45MB程度のswapファイルを作った所起動しました。

AtomCam2 ファームウェアバージョン4.58.0.66 にて確認。

原因までは追えていません。

**Comment by mnakada** [comment]
手元のAtomCam2 Ver.4.58.0.65, Ver.4.58.0.79で確認してみましたが、症状は発生しないようです。
可能であれば、
/etc/inittabのrcSの行に下のようにlogへのredirectを追加して
::sysinit:/etc/init.d/rcS >> /media/mmc/test.log

shellから
swapoff -a
rm /media/mmc/swap
reboot
で再現させてSD-Cardのtest.logをもらえると助かります。

**Comment by mnakada** [comment]
再現しないのでcloseします
