### ISSUE TITLE
Record video on demand

### ISSUE THREAD

**Issue by baudev** [mnakada/atomcam_tools#60]
Hi!

I'm looking for a way to record a video when launching a command. We could imagine for example:

```
cmd record_video file_path
```

Currently there are only two possibilities:

- record continuously
- record when a motion is detected

Is there a way to do it? 
Thanks

**Comment by gtxaspec** [comment]
enable RTSP, and you can use ffmpeg to record the rtsp stream locally on the camera, or on a remote computer.

**Comment by baudev** [comment]
Not really great for resource consumption but if that's the only way I'll do it, thanks!
