### ISSUE TITLE
ファイルの自動削除が recordフォルダー以外で動作しない

### ISSUE THREAD

**Issue by ohzaki** [mnakada/atomcam_tools#62]
SDカードのファイルの自動削除が recordフォルダーでは動作しますが，alarm_record とtime_lapse では動作しません
NASの方も同様のようです

**Comment by mnakada** [comment]
ありがとうございます。
Ver.1.5.8で修正しました。
手元で確認したところ、SD-Cardのみ動作してなかったようです。

**Comment by ohzaki** [comment]
ご対応ありがとうございます
