### ISSUE TITLE
ssh接続にてパスワードを聞かれる

### ISSUE THREAD

**Issue by ysmr3104** [mnakada/atomcam_tools#64]
atomcam_toolsにてATOM Cam Swingの利用を始めました。

タイトルの通りssh接続を行おうとすると、下記の通りパスワードを聞かれて認証できない状況になってしまいます。
初歩的な部分で恐縮ですがアドバイスいただければ幸いです。

> ssh root@atomcam.local
> root@atomcam.local's password:

本体環境としては
ファームウェアバージョン：4.37.1.102
Plub-in version：1.1.1.14

atomcam_toolsのバージョンは1.5.9です。
ping atomcam.localで名前解決できているので、hostnameは反映できておりブラウザアクセスによる操作もできております。

クライアント環境はmacOS 13.0.1（22A400）で、基本的なssh設定はできている認識と思っております。

鍵作成時のコマンド
> ssh-keygen -q  -t rsa -b 4096 -C '' -N '' -f id_rsa

クライアント.sshフォルダ
> ls -la .ssh
> total 32
> drwx------   6 ysmr  staff   192 12  7 22:00 .
> drwxr-xr-x+ 50 ysmr  staff  1600 12  7 22:15 ..
> -rw-------   1 ysmr  staff    45 12  7 21:56 config
> -rw-------   1 ysmr  staff  3357 12  7 22:00 id_rsa
> -rw-------   1 ysmr  staff   726 12  7 22:00 id_rsa.pub
> -rw-r--r--   1 ysmr  staff   190 12  7 21:57 known_hosts
> 

SDカード内のファイルリストは以下のとおりです。

> ls -l /Volumes/ATOMCAM01
> total 531648
> -rwx------  1 ysmr  staff         62 12  7 12:50 atomhack.log
> -rwx------@ 1 ysmr  staff        726 12  7 22:03 authorized_keys
> -rwx------  1 ysmr  staff    1048576 12  7 13:01 configs
> -rwx------@ 1 ysmr  staff    2385363 12  7 21:48 factory_t31_ZMC6tiIDQN
> -rwx------  1 ysmr  staff         26  1  1  1980 hack.ini
> -rwx------@ 1 ysmr  staff          8 12  7 21:48 hostname
> drwx------  1 ysmr  staff      32768 12  7 12:49 log
> -rwx------@ 1 ysmr  staff  134217728 12  7 13:00 rootfs_hack.ext2
> -rwx------  1 ysmr  staff  134217728  1  1  1980 swap
> -rwx------  1 ysmr  staff         20 12  7 13:01 time.ini
> drwx------  1 ysmr  staff      32768 12  7 12:49 time_lapse
> drwx------  1 ysmr  staff      32768  1  1  1980 tmp
> drwx------  1 ysmr  staff      32768  1  1  1980 update
> -rwx------  1 ysmr  staff         15  1  1  1980 update.log

基本的な所で躓いてしまい恐縮ですが、アドバイスいただければ幸いです。

**Comment by mnakada** [comment]
登録したpublic keyとsshでloginしようとした時のsecuret keyがどこかで食い違っている場合にパスワードを聞かれる状態になると思います。
.ssh/config等で他のkeyを指定したりして無いでしょうか？
ssh -i ~/.ssh/id_rsa root@atomcam.local
とsecuret keyを指定しても同じですか？
あとはauthorized_keysの鍵が.ssh/id_rsa.pubと同じになっていることを確認するくらいですね。
あまり助言になっていなくてすみません。

**Comment by ysmr3104** [comment]
ご返答ありがとうございます。
他にssh使う用事は特に無いので、~/.sshディレクトリから再作成してkeyの再作成してみましたが解消しませんでした。
※念の為ATOM Cam SwingのRESETボタン15秒によるリセット＆再登録、SDカード初期化からのatomcam_tools再設定（authorized_keysの上書き含む）も併せて実施

> ssh -i ~/.ssh/id_rsa [root@atomcam.local](mailto:root@atomcam.local)
こちらも実施いたしましたが同様でした。

もう少し試行錯誤してみます。

**Comment by ysmr3104** [comment]
sshの目的がファイル取得でwgetで代替できそうなので一旦sshはあきらめます。
ありがとうございます。

**Comment by mnakada** [comment]
Host側のOpenSSHのVersionが8.8以降だとRSA認証が無効化されているそうです。
これが原因なら、
`# ssh-keygen -t ed25519`
でED25519の鍵を作ってid_ed25519.pubをauthorized_keysに設定、
`# ssh -i ~/.ssh/id_ed25519 atomcam.local`
でloginできるようになると思います。
