### ISSUE TITLE
デバイス再起動後にデバイス名がデフォルトに戻る場合がある

### ISSUE THREAD

**Issue by horixs** [mnakada/atomcam_tools#68]
いつも便利に使わせていただいています。
自分の使っているAtomCam2の1台だけなのですが、デバイスを再起動させるとデバイスの名前がデフォルトの「atomcam」に戻ってしまうのがあります。

そのデバイスのweb設定を見るとデフォルトの名前に戻ってますが再度設定すれば問題はありません。
また、純正Atomアプリでは設定していたデバイスのままになっています。
他に設定している同じAtomCam2は再起動後にすぐ設定名に切り替わっているのを確認できます。

これは単純にデバイスやSDカードが悪いでしょうか？

安定化を試すため、1週間に1回定期再起動をしていてNAS保存でフォルダ名がデフォルトのがあるので気付きました。
録画データも連続撮影にしていますが、1分区切りのはじめ部分「00:00:00～00:00:10」秒くらいの間でたまに録画がコマ落ちor止まっている状態が多かったので再起動を定期的にしてみようと思ったわけです。
＊上記録画の頭が録画不安定になるのはWi-Fiエリアの結構ギリギリに置いているせいかなとも思っていたりはしますが。

どうぞよろしくお願い致します。

**Comment by mnakada** [comment]
起動時にSD-Cardに保存してある設定値を読み込んでいます。
SD-Cardにうまく書き込めていないか、読み込めていないかのどちらかと思います。
別のSD-Cardで一度試してみると問題を切り分けできるかもしれません。

**Comment by horixs** [comment]
ご返答ありがとうございました。
とりあえずSDカードを変えて試してみます。
ありがとうございました。
