### ISSUE TITLE
atomcam swing bootloader

### ISSUE THREAD

**Issue by gtxaspec** [mnakada/atomcam_tools#69]
@mnakada,

greetings.  I am wondering if you own a model atomcam swing.  I am interested in obtaining the bootloader partition image (/dev/mtd0)...

if you do, or if anyone who does sees this, would you be to kind as to share it?

thank you.

**Comment by accept** [comment]
https://1drv.ms/u/s!Aob34YvSSj56g5lgrCGjiz_KAnYXQw?e=XW3j8y

**Comment by gtxaspec** [comment]
I could swear someone posted an image here, but i no longer see it.  

???

**Comment by mnakada** [comment]
I don't know.
Maybe it was removed due to rights issues.

**Comment by arguser** [comment]
@gtxaspec Here https://github.com/escapingnetwork/campanario/tree/TELEAR_CamPan/bootloader you can close this issue now :)

**Comment by gtxaspec** [comment]
@arguser thanks so much!

**Comment by arguser** [comment]
@gtxaspec you are welcome!! I suspect the Wyze Cam Pan V3 and mine are quite similar in features. Any help you can provide on this https://github.com/mnakada/atomcam_tools/issues/74 would be appreciated!!
