### ISSUE TITLE
定期リスタートの時間設定が効かない

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#7]
定期リスタートの時間設定が効かない

長期運用時にATOM CAM2が音信不通になることがあるため毎日定時に再起動させています。
定期リスタート機能のおかげで、音信不通になっても定時に復旧できるようになり助かっています。

ATOM CAM2　3台でテストしています。
月曜日から日曜日まで毎日14時ごろ再起動する設定です。
設定情報、確認情報は次の通りです。
動作環境3台とも
ATOMCam2 Ver.4.58.0.65
atomcam_tools Ver.1.2.15

毎日再起動は実行されていますが時間は02:00です。

設定に不備がありましたら、ご指摘ください。
よろしくお願いします。

1台目　月曜日から日曜日　14:02
/atom/tmp/hack.ini　の内容
cat /atom/tmp/hack.ini
DIGEST=
REBOOT=on
REBOOT_SCHEDULE=2 14 * * 0:1:2:3:4:5:6
RECORDING_ALARM=on
RECORDING_LOCAL_SCHEDULE=off
RECORDING_LOCAL_SCHEDULE_LIST=
RTSPSERVER=off
RTSP_OVER_HTTP=off
RTSP_AUDIO=off
STORAGE_SDCARD=on
STORAGE_SDCARD_PUBLISH=off
STORAGE_SDCARD_PATH=%Y%m%d/%H%M%S
STORAGE_SDCARD_REMOVE=on
STORAGE_SDCARD_REMOVE_DAYS=1
STORAGE_CIFS=on
STORAGE_CIFS_PATH=%Y%m%d/%H%M%S
STORAGE_CIFS_REMOVE=on
STORAGE_CIFS_REMOVE_DAYS=5
STORAGE_CIFSSERVER=//192.168.100.30/Share
STORAGE_CIFSUSER=
STORAGE_CIFSPASSWD=
WEBHOOK=off
WEBHOOK_URL=
WEBHOOK_ALARM_EVENT=off
WEBHOOK_ALARM_INFO=off
WEBHOOK_ALARM_VIDEO_FINISH=off
WEBHOOK_ALERM_VIDEO=off
WEBHOOK_ALARM_PICT_FINISH=off
WEBHOOK_ALERM_PICT=off
WEBHOOK_RECORD_EVENT=off
WEBHOOK_TIMELAPSE_EVENT=off
WEBHOOK_TIMELAPSE_FINISH=off
MINIMIZE_ALARM_CYCLE=off
[root@atomcam010:~]#

2台目　月曜日から日曜日　14:03
REBOOT_SCHEDULE=3 14 * * 0:1:2:3:4:5:6

3台目　月曜日から日曜日　14:07
REBOOT_SCHEDULE=7 14 * * 0:1:2:3:4:5:6

atomhack.log　に再起動時間が記録あり、3台とも02:00に再起動をしているようです。
1台目
Fri Apr  1 01:27:12 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      63660      10532          0        524      15012
-/+ buffers/cache:      48124      26068
Swap:       131068      14140     116928
2022/04/01 02:00:30 : Reboot & Start watchdog
Fri Apr  1 03:01:01 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      65984       8208          0        536      20956
-/+ buffers/cache:      44492      29700
Swap:       131068       9044     122024

2台目
Fri Apr  1 01:25:05 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      62024      12168          0        380      19644
-/+ buffers/cache:      42000      32192
Swap:       131068      19456     111612
2022/04/01 02:00:32 : Reboot & Start watchdog
Fri Apr  1 03:01:19 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      67328       6864          0        676      24852
-/+ buffers/cache:      41800      32392
Swap:       131068      12072     118996

3台目
Fri Apr  1 01:21:06 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      71432       2760          0         96      25140
-/+ buffers/cache:      46196      27996
Swap:       131068      21520     109548
2022/04/01 02:00:37 : Reboot & Start watchdog
Fri Apr  1 03:01:13 JST 2022
             total       used       free     shared    buffers     cached
Mem:         74192      68360       5832          0        524      20484
-/+ buffers/cache:      47352      26840
Swap:       131068      11376     119692

**Comment by mnakada** [comment]
手元の
ATOMCam2 Ver.4.58.0.65
atomcam_tools Ver.1.2.15
では再現できなかったので、お手数ですが
cat /var/spool/cron/crontabs/root 
を確認してもらえますか？

**Comment by kurokouji** [comment]
cron確認しました、内容は次の通りです。
ここでは02:00になってますね。
よろしくお願いします。

cat /var/spool/cron/crontabs/root
*/15 * * * * /usr/sbin/logrotate /etc/logrotate.conf
0 * * * * /scripts/remove_old.sh
0 2 * * 7 /scripts/reboot.sh
[root@ck-cycle:~]#

**Comment by mnakada** [comment]
Ver.1.2.16で対応しました。
update時にrootfsを更新していますが、crontabへの反映が抜けていました。

**Comment by kurokouji** [comment]
早速対応いただきありがとうございます。
Ver.1.2.16にアップデートして数日、様子を見てみます。
また、不具合があるようでしたらお知らせいたします。

sshで　tail -f /atom/tmp/log/atom.log　を実行し状況を観察していると
ATOMCam2との音信不通の原因と対策も見つけられそうです、素晴らしいツールの公開感謝します。
