### ISSUE TITLE
ルータを変更した時のリセット操作で、ルータへのパスワードを受け付けない。

### ISSUE THREAD

**Issue by Hidenori-Kaga** [mnakada/atomcam_tools#70]
プログラム初心者です。
このような素晴らしいソフトを公開していただき感謝しております。

私の所でツールを入れた正常に動作しているAtomCam2を、離れてた家族の所へ持って行き、設置しようとして、
リセットでQRコードが読み込まれ、そこまでは通常だったのですが、ルータのパスワードが違うとの反応で受け付けてくれません。
SDカードを外して接続すると正常に接続が出来て動作しています。数台利用していますので操作ミスはないと思います、

ルータを変更した場合、新しくツールを書き込んだSDカードしか正しく動作しないのでしょうか。
移動する際は何らかの設定を変えておく必要があるのでしょうか。

よろしくお願いします。

**Comment by mnakada** [comment]
atomcam_toolsはWiFi設定を起動時に読み込むので、QRコードで設定したあと電源を再起動してください。
カメラのアプリと通信している部分で変更されたことをtoolsが検知できないため、電源の再起動が必要になります。

**Comment by Hidenori-Kaga** [comment]
一旦、SDカードを抜いて、リセットし、QRコードを読み込んだ後、再度ＳＤカードを挿し、電源を入れるという手順になるのですね。
ご返事、有難う御座いました。
