### ISSUE TITLE
Incorrect Media Type

### ISSUE THREAD

**Issue by admtan** [mnakada/atomcam_tools#72]
Firstly, I want to thank you for providing this valuable software. I noticed a minor issue and wanted to create an issue for it.

In `hack_ini.cgi` and `cmd.cgi`, the `Content-Type` specified seems to be incorrect. The current code indicates `plain/text`, but according to the RFC definition, it should be `top-level type/subtype`. For plain text, the correct format is `text/plain`. So, the string output by the echo command should be `Content-Type: text/plain`.

While this might not cause any issues when using only the Web UI and not directly accessing CGI, I kindly suggest fixing it as a precaution.

Thank you.

**Comment by mnakada** [comment]
I have corrected it in Ver. 1.5.14.

**Comment by admtan** [comment]
Thank you to fix!
