### ISSUE TITLE
インターネットに接続せず、イントラネット内での運用

### ISSUE THREAD

**Issue by akibo3g** [mnakada/atomcam_tools#73]
インターネットには接続させず、イントラネット内でウェブカメラを使いたく考えています。
NASモーション検知録画を使用し、イントラネット内のNASへ録画したいのですが、
インターネットに接続してないためか実行しない状況です。
他にもWebhookを試してみましたが、同様の状況です。
設定等で変更することでイントラネット内での運用は可能でしょうか？

【機器のファームウェア】
ATOMSwing Ver. 4.37.1.102
【atomcam_tools】
Ver.1.5.12

**Comment by mnakada** [comment]
検知機能はatomtechのawsサーバーから起動時に読み込まれて実行されるようです。
そのためインターネットに繋がらない環境だと読み込み出来ないため検知機能が働かないです。

**Comment by akibo3g** [comment]
早急の回答ありがとうございます。
