### ISSUE TITLE
【機能追加希望】死活監視NG時自動再起動

### ISSUE THREAD

**Issue by ipv6hack** [mnakada/atomcam_tools#76]
本ソフトにはいつもお世話になります
機能追加希望です
特定のIPアドレス（例：宅内のHGWのLAN側IPアドレス）等に定期的に死活監視をし、
NGの場合、ATOM　CAM、CAM2、SWINGを自動再起動というのを希望いたします
理由はWIFIで長時間見ていると時々カメラ側のWIFIが切れることがあります
現在はATOMカメラのコンセント部分にスマートコンセントを接続してそれで手動で
電源OFF/ONをしていますが、何とか自動にならないものかと思い記載いたしました
よろしくお願いいたします

**Comment by ipv6hack** [comment]
お返事ありがとうございます
Codeのページに記載がなかったので死活監視＆リブート機能がないものと思っておりました
>DNSでdefault gwが引けていることが条件ですが。
DNSでdefault gwが引けるとはどういうことでしょうか？
DHCPで・・・・の誤記でしょうか？

DHCPではデフォルトゲートウェイは払い出しているのですが、時々ATOMのアプリから
カメラが疎通できなくなるので困っておりました
本ソフトは入れているのですが、最新ではなかったのでとりあえず最新にしてみて少し様子を見てみます

**Comment by mnakada** [comment]
すみません。DHCPの間違いです。
ネットワーク関連の問題が発生した時にSD-Cardのhealthcheck.logに記録されます。
１分ごとに実行されているscriptはoverlay_rootfs/scripts/health_check.shになります。
問題解決の参考になれば。

**Comment by ipv6hack** [comment]
お返事ありがとうございます
ログの確認も含めて参考にさせていただきます

**Comment by ipv6hack** [comment]
機能が具備されているのでクローズいたします
