### ISSUE TITLE
support for 4.37.1.102 firmware

### ISSUE THREAD

**Issue by mogorman** [mnakada/atomcam_tools#78]
I am trying to get this working on my atom cam swing camera.  When I insert the sd card with the files it will not connect to my wifi. If i hit the setup button it will prompt me for qr code, and accept it. But after a long time it will eventually say it has no internet connection. rebooting the camera with out the sd card restores it back to a working order. Am I doing something stupid?

**Comment by mogorman** [comment]
also according to atom this is the latest version? I cant upgrade to 4.37.1.106

**Comment by mogorman** [comment]
when i installed the test app the only version i can upgrade to is 4.37.1.135

**Comment by GeckoLink-com** [comment]
The first time, setup without SD-Card and check the connection.
Then insert the SD-Card for atomcam_tools and reboot.
The SD-Card must be formatted with FAT32.
