### ISSUE TITLE
ATOMCAMのファームアップデート後にatomcam_toolsを含むSDカードで起動するとSDカードを認証しない。

### ISSUE THREAD

**Issue by jctk** [mnakada/atomcam_tools#80]
ATOM CAM Swingのファームウェア 4.37.1.141 にアップグレード後、atomcam_tools が含まれる SDカードを使用するとアプリで以下の現象が発生します。
atomcam_tools のバージョン 1.5.14

ATOM CAM Swingのファームウェアアップグレード前ではこのような現象は発生していません。
atomcam_tools を含まないフォーマット直後の SDカード ではこの現象は発生しません。
iOS版のアプリおよびAndroid版のアプリ（Windows Subsystem for Androidで使用）のいずれでも発生します。

atomcam_tools を導入するとアプリから SDカード を認識できないようになることはありうるのでしょうか？

手順
1. 32GBのSDカードに atomcam_tools を導入。authorized_keys はファームアップグレード前から使用していた鍵を含みます。
2. ATOM CAM Swing のACアダプターをコンセントから外す。
3. ATOM CAM Swing に SDカードを挿入し、ACアダプターを電源に接続する。
4. Wi-Fiに接続したころに ATOMCam Hack に接続できることを確認。
5. iOSでアプリを起動（カメラの接続に時間がかかる）。何度かアプリの再起動をし接続される。（atomcam_toolsを含まないSDカードでは接続もすぐ行われます。）
6. アプリに接続された後に、動画のすぐ下の動画録画ボタンが灰色になっている。
7. アプリの録画を再生ボタンをタップすると添付の画像の通り、SDカードが挿入されていないと表示される。
8. SFTPでATOM CAM Swing の /media/mmc/record フォルダーを確認すると動画ファイルがあり録画はされている。

![iOS](https://github.com/mnakada/atomcam_tools/assets/52247294/cd450869-b745-4bab-9c9e-452e7fa5e64f)

**Comment by jctk** [comment]
追伸
新しいファームウェアのATOM Cam swingでatomcam_toolsを使用いていると、
アプリからカメラに接続しにくい、
赤外線ライトがいつのまにかオンになる、
アプリで向きを変えようとしてもなかなか受け付けない、
アプリを操作しているといつのまにかカメラが再起動する
などの症状もあるようです。

よろしければ対策などしていただければ幸いです。
よろしくお願いいたします。

**Comment by mnakada** [comment]
負荷を軽減したお試し版を
https://github.com/mnakada/atomcam_tools/releases/tag/Ver.2.0.0pre1
に置きました。
最近のATOM Camの本体が肥大化してきているのでメモリ不足で重たくなっています。
少し前のATOM CamのVerを使ってもらう方が安定しています。

**Comment by jctk** [comment]
更新ありがとうございます。
週末に確認させていただきます。確認後こちらに結果を共有します。

**Comment by jctk** [comment]
2.0.0pre1の動作を取り急ぎ画面で確認をいたしました。
ATOMCam Hack Setupの画面に表示されているバージョンが1.5.14のままですが内容は2.0.0pre1になっていると考えてよろしいでしょうか。
2.0.0preおよびATOM Cam Swingのファームウェア更新を以下の手順で行いました。

1. ATOM Cam Swing をアプリから OFF し ATOM Cam Swing のUSBを電源から外す。
2. SDカードをATOM Cam Swingから抜き出し、PCで2.0.0pre1のfactory_t31_ZMC6tiIDQNとrootfs_hack.squashfsをSDカードのルートに保存する。
3. ATOM Cam Swing のUSBを電源に接続し、アプリでファームウェアを4.37.1.142にバージョンアップ。
5. ATOM Cam Swing をアプリから OFF し ATOM Cam Swing のUSBを電源から外す。
6. SDカードをPCから取り出しATOM Cam Swingに挿入する。
7. USBを電源にさす。

**Comment by jctk** [comment]
動作の確認をしました。
ATOM CAM Swingのファームウェアを4.37.1.141に更新し、2.0.0pre1を使用しました。
atomcam_toolsはWeb画面での操作とRTSPでのストリーミングが可能なことを確認しました。
iOSのアプリの動作が不安定なのは変わりませんでした。

> ATOM Cam Swingでは最近のVerは重たくなってきてるのでお勧めしません。

とのことですので、現在はATOM CAM Swingのファームウェアを4.37.1.102に、atomcam_toolsを1.5.14にダウングレードしました。

ちなみにatomcam_tool 2.0.0pre1はATOM CAM Swingのファームウェアを4.37.1.102でも動作しないのが正しい動きでよろしいでしょうか？

**Comment by mnakada** [comment]
手持ちのswingだとpre1とVer.4.37.1.142の組み合わせでも重たいですが動いてはいます。
但し、iCamera_appの負荷がCam2と比べて10%程度重たいためAI検知アラートなど重くなる設定をoffにしています。
また、SD-Cardのネットワークアクセス（Samba)はoffにしてSD-Cardを見たい場合はSD-Cardファイル表示のwebアクセスで使っています。
できるだけ使わない機能はiOSアプリもtoolsもoffにすることで負荷を下げることができます。
全体的にメモリが足りてないためswingでは厳しいですね。
たまにiCamera_appのプロセスが落ちてしまって再起動かかる現象も見受けられます。

**Comment by jctk** [comment]
設定次第でVer.4.37.1.142との組み合わせでも動作するとのことですね。
今後どの組み合わせで使用するは検討いたします。
いろいろとご対応ありがとうございます。
