### ISSUE TITLE
ATOMCAM Swing 4.37.1.142 にバージョンアップ後 atomcam_toolsの課題が発生

### ISSUE THREAD

**Issue by takeshi56** [mnakada/atomcam_tools#81]
atomcam_toolsのお世話になっております。対応ファームウェアでは無い点承知の上でバージョンアップしましたところ、下記の事象に遭遇しています。なお、手元には3台の稼働中Swingがありまして、それぞれで事象が異なります。

Swing1
- ssh接続が出来なくなった
- クルーズスケジュールに合わない動作をする(追尾動作後にスケジュールタイムが来て、設定したポジションに戻る)

Swing2

- ssh接続が出来なくなった
- 初期化・atomcam_toolsの再展開をしても起動してこない
- pingだけは応答がある

Swing3

- ssh接続が出来なくなった
- 初期化・atomcam_toolsの再展開をしても起動してこない(アンバーランプ点灯)
- ping応答無し

SDカードを抜いて、ファイルをZIP等で固めてアップロードすることは出来ますが、必要なログ等確認するところがありましたらご指示ください。

**Comment by mnakada** [comment]
負荷を軽減したお試し版を
https://github.com/mnakada/atomcam_tools/releases/tag/Ver.2.0.0pre1
に置きました。
最近のATOM Camの本体が肥大化してきているのでメモリ不足で重たくなっています。
少し前のATOM CamのVerを使ってもらう方が安定しています。

**Comment by takeshi56** [comment]
ありがとうございます。自宅に帰ったら早速試して見ます。
ツールの立ち位置として元のファームウェアの利用リソース次第ですので、
不用意にバージョンアップするのはよくありませんね。

2024年1月15日(月) 21:39 Mitsuru Nakada ***@***.***>:

**Comment by takeshi56** [comment]
2.0.0がtoolのupdateで表示されたので、アップデートしまして成功しました。
sshでTerminal接続出来ていなかったのが出来るようになっておりまして、負荷も下記の様な状況で以前より良くなっています。
"
[root@carport2nd:~]# uptime
 18:33:54 up 5 min,  load average: 5.41, 5.16, 2.44

ATOMの公式アプリから動画データが取得がしづらい状況です。何かにつけて(sshしたり、wpa_cli statusしたり)アクションすると
ストリームが落ちるような状況です。やはり、現在のファームウェアが重たいのでしょう。
ただし、sshが出来るようになりましたので、atom.log等の取得は楽になりました。

**Comment by mnakada** [comment]
Ver.2.2.0以降で負荷を削減しました。
