### ISSUE TITLE
Ver.2.0.0pre1を試し中・・・

### ISSUE THREAD

**Issue by katsumiota** [mnakada/atomcam_tools#82]
こんにちは。現在ATOM Cam 2×2台、ATOM Cam Swing×2台、ATOMアプリVer3.10.18と言う環境で運用しています。
toolは結構前から便利に利用させて頂いています。ありがとうございます。Swingではファームバージョン4.37.1.102+tool Ver.1.5.14、Cam2ではファームバージョン4.58.0.108+tool Ver.1.5.14の組み合わせでは特に問題なく利用できています。

新しいファームが出るたびに更新してtoolが利用できるか確認していますが、今書いたバージョンの組み合わせ以外では駄目で困っていました所、先日新しいtoolのバージョン「2.0.0pre1」をリリースして頂いてることを知ってSwingとCam2共にファームを現在の最新（Swingは4.37.1.142、Cam2は4.58.0.115）にした上でtool「2.0.0pre1」を入れて現在試している状態です。現時点で気がついた事は、通信が不安定と言いますか、Wi-Fiに繋がりにくかったり繋がらなかったり、ライブ映像を見ているときでも通信速度が徐々に落ちてきて切断されたりとか、他には動作に負荷が掛かっているせいなのか（特にSwing）設定とかの変更をする際とか結構いろんな場面で「クルクル？」が表示されます。Cam2はそんなには問題なく使えていますがSwingはモッサリな感じです。
なお、toolを入れていない状態では勿論問題なくカメラ映像を見たり出来ます。

以上、ご報告をさせて頂きました。又何かありましたら書き込ませて頂こうかと思っています。

**Comment by mnakada** [comment]
Ver.2.2.0以降で負荷を削減したので軽くなったかと思います。

**Comment by katsumiota** [comment]
mnakada様、こんばんは。返信ありがとうございます。現在のバージョンはVer.2.2.0ですが、仰るとおりVer.2.0.0pre1の時よりもかなり軽くなりほぼ問題なく動作しているように感じています！
色々と大変なこともあるかとは存じますが、今後も更新を続けて言っていただけますと、うれしいです。よろしくお願いいたします。
