### ISSUE TITLE
ATOMCAM Swingを公開してswingのみ使用させる

### ISSUE THREAD

**Issue by tokaref567** [mnakada/atomcam_tools#85]
ATOMCAM Swingを公開してswingのみ使用させる方法はないでしょうか
普通にそのまま公開すると、録画を消されたり、何でもできるのですが
カメラのswingのみ使用させ、皆に遊んでもらえる設定ができたら、
皆に公開したいと思うのですが、可能でしょうか

**Comment by mnakada** [comment]
kernel等も古くsecurity riskがあり、ATOMCamのアプリがWiFiのSSIDとパスワードを生値で保存していたりするのでATOMCamを直接公開することはやめた方がいいです。
外に公開したい場合はRasPi等で中継してSecurityを確保して出すようにしてください。

**Comment by tokaref567** [comment]
wifiのSSIDはguestで使って、中には入っておれないようにしてます。
壊されるのは仕方ないです。踏み台は怖いですが
あのswingが皆が操作できたら、面白がってくれるかなと
厨房をDIYしてるので、公開できたらなど
魚眼でLIVE配信などは試してるのですが、も一声遊び心が欲しいなと
アプリを入れずに操作できる装置が、見つからなく しかもスイングが魅力的で
そういった、装置やソフトがあれば、それも教えて頂けたらありがたいです。

**Comment by admtan** [comment]
ようは curl で言う以下のようなリクエストが安全に Swing へ送れればいいんですよね
```curl
curl 'http://example.com/cgi-bin/cmd.cgi?port=socket' -X POST -H "Content-Type: application/json" -d '{"exec":"move 100 80"}'
```
リバースプロキシーを立てて、それ越しにリクエストを送れるようにすればいくらか安全ですが、`cmd.cgi` は上記の操作以外もできますので、`move` しか受け付けないスクリプトを用意しないと結構リスクです。

技術的には可能ですが需要はあまりないかもしれません。(私の友人が似たような仕組みで工房を公開したい的なことを言っていたので私自身の興味はあります)

**Comment by tokaref567** [comment]
ありがとうございます。
確かに個人では、需要はないに等しいのですが、youtubeがこれだけ世の中に流行ったという事は
見せたい人も多いのかなと？？？

観光系の業務を行ってる方などは、面白がると思います。
発想は、弁当屋さんでlive配信を行ったところ、万引きが減り
更に、そのlive配信で客が多くなったと
私の場合は、ビジネスより、ＤＩＹの遊び心共有できたらなと思ってます。
ですが、知識があまりにも乏しいもので、何か教えて頂けたらありがたいです。
どう探しても、スイングをIPで触れる物が無くて

**Comment by tokaref567** [comment]
理論的には、Telnet系で入れなくして
表示上、画面だけ出るようにしたらいいだけなのかと
私には、そのスクリプトの書き方がわからなくて
