### ISSUE TITLE
WiFi切断でATOMCam2のシステム時計が遅れる

### ISSUE THREAD

**Issue by oamackerel** [mnakada/atomcam_tools#86]
WiFi切断状態でこのtoolsを使うとATOMCam2のシステム時計が遅れます。
1時間に約2.5分、１日に約60分程度遅れます。
WiFiを接続したままだと遅れません。toolsのWebUIやandroidアプリの接続をしなくとも遅れません。
WiFi切断状態から再接続すると時刻が校正されます。
オリジナルのまま無改造の場合、1日間、WiFi無接続でもほとんどくるいはありません。
セキュリテイの心配のため必要な時だけWiFi接続して、普段は無接続で運用したいと思います。

ATOM Cam2 Ver.4.58.0.115
ATOMCam Hack Ver2.1.2

**Comment by mnakada** [comment]
定期的にWiFiの接続確認をしていて繋がらないと再起動しています。
再起動時に時刻が取れないため、最後に記録した時刻から始まるため時刻が遅延していきます。
Ver.2.1.3でWebUIにモニタリング - Network確認、異常時再起動を追加したのでoffに設定してください。
WiFiの確認と再起動をしなくなります。

**Comment by oamackerel** [comment]
バージョンアップ対応ありがとうございます。
WiFi接続間隔6時間で2回試した結果、遅れはありませんでした。
これで、気になることがあったときだけWiFi接続をして確認ができます。
wgetで複数ファイルを一括ダウンロードし、ffmpegで1ファイルに結合、
VLCで32倍速で見ることが実用的になりました。
たいへん感謝します。

ATOMCcam Hack ver.2.1.3
ATOM_CamV3C Ver.4.58.0.115 (ATOM Cam2)
