### ISSUE TITLE
録画データの分割時間について

### ISSUE THREAD

**Issue by horixs** [mnakada/atomcam_tools#88]
いつも便利に利用させていただいています。
個人的にあるといいなと思ったことをお聞きします。

今、NAS録画（SDカード録画もでしょうか）で保存される録画データは1分間隔ですが、これを例えば5分間隔で保存できたりはしないでしょうか？
私の環境だと、1分間隔だと毎時02秒位から5～10秒位コマが動かなくなるパターンが時たまあります。
Wi-Fiのエリアギリギリとか設置環境が大いに影響を与える部分も大きいと思いますが、1分ではなく１～５分の間隔で録画データの保存ができたりするありがたいですね。

最近のメモリの少なさから難しいかもしれませんが、可能な話だったりするのでしょうか？
駒落ちしているところはファイル転送にかかっている負荷のところだったりするかもしれませんが。

AtomCam2 FW:4.58.0.115
AtomCam Swing FW:4.37.1.42
ATOMCamTool Ver2.1.5

**Comment by mnakada** [comment]
録画時間は製品のアプリの中で設定されているので変更はできないです。

**Comment by horixs** [comment]
製品仕様なのですね、分かりました。
ご回答ありがとうございました。
