### ISSUE TITLE
timelapse動画を再生すると途中で止まる

### ISSUE THREAD

**Issue by ohzaki** [mnakada/atomcam_tools#89]
timelapse動画を以下の設定にしています
出力fps: 60
毎日 06:00 (～翌日05:55まで)
周期 24秒 3588回

timelapse動画は保存はされていますが，実際に再生してみると，開始から10時間経過した頃に再生が止まってしまいます
次の録画開始までの間隔が5分と短いのが原因かと思い，20分ぐらい間を空けても状況は変わりませんでした
開始時刻を変えても，やはり開始から10時間経過した頃に再生が止まってしまいます
10(h) x 60(m) x 60(s) / 24(s) = 1500 で 1500コマ分までしかtimelapse動画にできないのでしょうか？

**Comment by ohzaki** [comment]
直っていませんでした
ログを取れるように仕込んだので，ログが取れたらアップします

**Comment by mnakada** [comment]
コードを確認したところ問題箇所が判り再現できました。
多分、Ver.2.2.2で直っていると思います。

**Comment by ohzaki** [comment]
ありがとうございます
バージョンアップして確認してみますが，問題箇所が特定できたということで今度は大丈夫そうですね

**Comment by ohzaki** [comment]
直っていました
ありがとうございます
