### ISSUE TITLE
2.2.2アップデート後　定期リスタートの位置

### ISSUE THREAD

**Issue by Hiii555** [mnakada/atomcam_tools#90]
今まで定期リスタート後も元のポジションに戻っていたのですが、
2.2.2にアップデート後ポジションが変わってしまう気がします。

**Comment by mnakada** [comment]
どのVer間で変わったか判りますか？
手元のSwingが壊れてモーターが動かないので変更履歴からしか追えないですが。

**Comment by Hiii555** [comment]
2.2.1では再起動後元のポジションに戻っていました。
2.2.2から定期リスタート後XY座標が固定（110,138）になりました。

**Comment by mnakada** [comment]
2.2.1と2.2.2の間ではtimelapseのbug修正とUSB-Ether対応しか変更していないので影響しなさそうです。
timelapseに関してはフレーム数の計算修正だけですし、USB-EtherはUSBにデバイスが見つからなければ動作しないのでSwingのモーター位置に関連しそうなところは無いですね。

SD-Card上のconfigを保存しているファイルがfsckで修正できない状態になっているため起動ごとにSPI-Flashから読み込んでしまって固定値になってる可能性があります。
1.一度SD-Cardのconfigsというファイルを削除して再起動
2.それでも直らない場合は、SD-Cardを一度formatしなおして再度入れ直してみる
くらいしか思いつきません。

ダメな場合はVer.2.2.1に戻してください。

**Comment by admtan** [comment]
確証が持てなかったので Issue を立てていなかったのですが、私の環境でも発生します。(v.2.2.2, v4.37.1.142)
v2.1.x あたりから発生していたと記憶しています。曖昧ですみません。

**Comment by mnakada** [comment]
WebUIからカメラ位置を移動させて
sshでloginして
grep slide /atom/configs/.user_config
でslide_x, slide_yの値が移動させた値の100倍前後の値になってることを確認
再起動して
もう一度
grep slide /atom/configs/.user_config
の値を確認
その時の/media/mmc/atomhack.log
を送ってもらえますか。
長すぎるようなら最後の100行くらいだけで大丈夫です。

**Comment by Hiii555** [comment]
色々テストしてみました。定期リスタートで位置が戻ってしまう状態でしたが手動で「リブート」をすると
座標が変わらなくなりました。3月頭から使い始めたので2.1.4以降で何か位置が戻ってしまうと調整しても
定期リスタートで座標が戻る現象がでるのかなぁと思っています。2.2.2でも手動で１回リブート掛けると
座標は維持されました。

**Comment by mnakada** [comment]
あれ？定期リスタートが掛からなくなってる気がする。

**Comment by mnakada** [comment]
どうも現象が追いきれないですが、SD-Cardにあるhack.iniとatomhack.logファイルを送ってもらえないでしょうか？

**Comment by Hiii555** [comment]
2.2.2にしてから設定は飛んでいくようですが定期リスタート出来ないというか、録画も常時にしていたのが
3/14あたりから常時ではなくなっている気がします。座標はおそらくアプリで位置を動かしてしまい
帰宅後AtomcamHackで修正したもののアプリ側の位置情報が保持されていて上書きされないのが原因だと思いました。

**Comment by Hiii555** [comment]
直近数日のNASデータを見た所常時録画がアラートの様な感じがします。今からatomcam_tools入れてファイルお送りします。

**Comment by mnakada** [comment]
> 録画も常時にしていたのが3/14あたりから常時ではなくなっている気がします。

アプリの設定で
録画およびストレージ管理 > SDへのローカル録画 > 録画モード
が「モーション検知時のみ」になっていませんか？

**Comment by Hiii555** [comment]
一旦私の初期値3月頭の2.2.0 v4.37.1.142にしてSD初期化、NAS常時録画とタイムラプスを設定してみました。
NASの常時録画が上手く出来なくなってきたのが11日2.2.1にアップデートした時位です。10時前後から録画が
飛び飛びになっています。今定期リスタートを試した所NASへの録画も止まってしまった気がします。
本当に話がおかしくなって来てしまいましたが定期リスタート起点で挙動がおかしい気がします。
[atomhack.log.txt](https://github.com/mnakada/atomcam_tools/files/14627475/atomhack.log.txt)
[hack.ini.txt](https://github.com/mnakada/atomcam_tools/files/14627476/hack.ini.txt)

**Comment by mnakada** [comment]
/atom/configs/.user_configもいただけないでしょうか。
ssidとパスワードなどがあるので[NET]以降を消してください。

**Comment by Hiii555** [comment]
今2.1.3まで下げて再起動と電源オフオンしてみましたがNAS上にファイルも作られなくなり
定期リスタートもしなくなりました。
[user_config.txt](https://github.com/mnakada/atomcam_tools/files/14627581/user_config.txt)

**Comment by mnakada** [comment]
アプリの設定で
録画およびストレージ管理 > SDへのローカル録画 > 録画モード
を連続録画に設定してください。
recordType=3
なのでモーション検知時のみ録画になっています。
この設定だとモーション検知時のみファイルをmvしようとするので常時録画されないです。

**Comment by Hiii555** [comment]
録画は元に戻りました。アプリで設定変更した覚えがないのですが連続録画にした所NAS上に録画されています。
定期リスタートはサービスのリスタートという認識であってますか？リブートはカメラが動き初期位置？的な所に
戻りますが定期リスタートもこれで戻らないのか？という質問だったのですが現状2.1.3でもカメラ位置に動きがないので
問題は無いのですが、アプリで動かした翌日だったので位置はアプリ優先なのかと考えていました。

**Comment by mnakada** [comment]
定期リスタートはシステムの再起動をしています。定期リブートとした方がよかったですね。
動作としてはリブートと同じ処理になります。
どちらもWebUIかアプリの最後の状態に移動します。（あと勝ちです）

**Comment by Hiii555** [comment]
定期リスタート（リブート）は2.1.3でも効いてない様な気がしますし、アプリは完全に落として
リブートすると初期位置に戻ってしまいます(x138.y110)が余程好きなんですかねぇ・・・

**Comment by mnakada** [comment]
とりあえず、定期リスタートのbugがあるのでVer.2.2.3をリリースしました

**Comment by Hiii555** [comment]
2.2.3へ飛んでみました。リブートと同じ様な挙動にならないです。crontabには書かれているのですが
効いていない感じがします。

**Comment by mnakada** [comment]
再起動しないですか？
sshで入って
/scripts/reboot.sh
を実行してもrebootしないですか？
cronからはこれが呼ばれます。

**Comment by Hiii555** [comment]
そうですね。今crontabを見ていて
16 0 * * 1,0 /scripts/reboot.sh
からのreboot.shを直で走らせてみましたがコンソールも切れません。

**Comment by mnakada** [comment]
echo "==$(awk -F "=" '/^REBOOT *=/ {print $2}' /tmp/hack.ini)=="
を実行した時に
==on==
と表示されますか？

**Comment by Hiii555** [comment]
==on==
と表示されログにも走った形跡はあるんですが実際はリブート出来ていない状態です。
Mar 18 00:16:00 atomtools cron.info crond[2802]: USER root pid 3209 cmd /scripts/reboot.sh

**Comment by mnakada** [comment]
rebootコマンドは効きますか？
実行しているのは
  /scripts/cmd timelapse stop
  sleep 3
  killall -SIGUSR2 iCamera_app
  sync
  sync
  sync
  reboot
なので、行くはずですが。

**Comment by Hiii555** [comment]
単純にrebootコマンドだとコンソールは落ちカメラは回転し始めリブートが始まり
完了後はアプリでもWebUIでもない固定の座標138.110にレッツゴーします。

**Comment by mnakada** [comment]
cp /scripts/reboot.sh /media/mmc
でSD-Cardにコピーして
先頭の#!/bin/shの次に
set -x
を追加して
/media/mmc/reboot.sh
をじっこうして表示されたものを貼ってもらえますか

**Comment by Hiii555** [comment]
結果です。
[root@hiiicam:mmc]# /media/mmc/reboot.sh
+ HACK_INI=/tmp/hack.ini
+ awk -F = /REBOOT *=/ {print $2} /tmp/hack.ini
+ REBOOT=on
on
+ [ on
on = on ]

**Comment by mnakada** [comment]
あれ？2.2.3にupdateされてないように見えますね。
/scripts/reboot.shの3行目は
REBOOT=$(awk -F "=" '/^REBOOT *=/ {print $2}' $HACK_INI)
と^REBOOTになってるはずですが。
cat /etc/atomhack.ver 
で2.2.3と表示されますか？

**Comment by Hiii555** [comment]
アレ？と思いました。もしかしてアップデート・カスタムアップデートなどが原因なのでしょうかねぇ。

**Comment by mnakada** [comment]
先ほどもらったhack.iniの設定が
CUSTOM_ZIP_URL=https://github.com/mnakada/atomcam_tools/releases/download/Ver.2.2.0/atomcam_tools.zip
になっていてCUSTOM_ZIP=onなのでVer.2.2.0になっていませんか？

**Comment by Hiii555** [comment]
定期リスタートはするようになりましたが、NASへの録画が今度は止まってしまっています。
カスタムZIPアップデートとアップデートが混ざってしまいました。

**Comment by Hiii555** [comment]
あぁ。アップデートをしてアプリで見ると「モーション検知時のみ」に変更となりますね。

**Comment by mnakada** [comment]
Verを戻したりしているとアプリのconfigの設定がおかしくなってクリアされる場合があります。

**Comment by Hiii555** [comment]
アップデートの際「アプリでの録画確認」は気をつけよう。という事で解決できそうです。
この定期リブートやリブートごの座標指定を出来るようにできませんか？

**Comment by mnakada** [comment]
SD-Cardに起動後のscriptを置けるので
/media/mmc/post_icamera.sh
に
```
#!/bin/sh

sleep 5
/scripts/cmd move 80 50
```
とかでもできるかもしれません。
sleepの秒数は適当に初期動作が終わる程度の待ち時間ですね。

**Comment by Hiii555** [comment]
今スクリプトを作り
#!/bin/sh

sleep 5
/scripts/cmd move 212 130

としてリブートをしてみたところリブート前と同じ位置での再起動ができました！
色々と話しが前後左右で混乱させてしまい申しわけありませんでした。毎日定期リスタートさせるので
何か合った際にも１日待てば元通りの理想なカタチに仕上げられました。
NASへの録画も再起動前後でも問題なくできています。深夜遅くまでサポートありがとうございました！
唯一はやはり少し角度調整を力強くやってしまい水平方向の固定位置を決めるプラスチックを割ってしまった所ですｗ
