### ISSUE TITLE
動体検知の検知録画upload停止のスイッチが機能していない

### ISSUE THREAD

**Issue by oamackerel** [mnakada/atomcam_tools#92]
すばらしいtoolをありがとうございます。
さて、動体検知の検知録画upload停止のスイッチがONでもoffでもATOMサーバーにuploadされます。
私が試した結果は次のとおりです。恐縮ですが調査をお願いします。

V.2.1.3 OK　uploadされません。
V.2.1.4 NG スイッチが効きません。ONでもoffでもuploadされます。設定ボタンのクリックは確認済み。リブートしても変化なし。
以降のバージョンで同じ

私の環境
製品型番 ATOM Cam 2
ファームウエアのバージョン Ver.4.58.0.115
プラグインバージョン 1.0.1

          oamackerel

**Comment by mnakada** [comment]
次のリリースで修正します。

**Comment by mnakada** [comment]
Ver.2.3.0で修正しました。

**Comment by oamackerel** [comment]
修正版のuploadありがとうございます。
試した結果うまく動作しています。
実用的な機能の追加がとてもうれしいです。
　　　　　　　　　oamackerel
