### ISSUE TITLE
WyzeCamV3対応(experimental release) 対応ファーム　報告

### ISSUE THREAD

**Issue by kurokouji** [mnakada/atomcam_tools#94]
いつも利用させていただいています。
WyzeCamV3対応　ありがとうございます。
過去に購入したWyzeCamV3を引っ張り出して検証してみました。
V4.36.9.139で動作確認いたしました。
![image](https://github.com/mnakada/atomcam_tools/assets/933671/863869ea-0b31-42bc-999e-d19642f9eaa9)
ファームを最新V4.36.11.8391にバージョンアップしたところ動きませんでした。
少し戻してV4.36.11.7017も動きませんでした。

古いバージョンのファームこちらに戻して復旧しました。
https://download.wyzecam.com/firmware/v3/demo_wcv3_4.36.9.139.zip

**Comment by mnakada** [comment]
ありがとうございます。
V4.36.9.139より後は動きません。iCameraがstatic linkでつくられているためです。

**Comment by kurokouji** [comment]
回答ありがとうございます。
ファームウェアの更新の注意に記載いただきましたので、こちらのissueはcloseします。
