### ISSUE TITLE
動作検知周期の短縮が出来なくなった。

### ISSUE THREAD

**Issue by hidetomo1969** [mnakada/atomcam_tools#95]
いつもお世話になっております。
便利なatomcam_toolsを使用させて頂きありがとうございます。
早速ですが2日ほど前から動作検知周期の短縮が出来なくなりました。
それまでは問題なく30秒で検知して録画されていました。
スイッチを30秒にして設定を押し再起動をかけても5分でしか機能しません。
atomcam_toolsのバージョンを2.3.0～2.2.1まで試しましたが結果は同じでした。
お忙しいところ申し訳ございませんが調査をお願い致します。

環境
ATOM Cam Swing
ファームウェアバージョン 4.37.1.102

**Comment by Hiii555** [comment]
18と19日の間で起こっている様でした。あまり気に留めてなかったのですが明らかに違いがありました。

**Comment by mnakada** [comment]
Ver.2.3.1で修正しました

**Comment by hidetomo1969** [comment]
お忙しいところありがとうございます。
確認致しました。
今後も宜しくお願いいたします。
atomcam_tools最高です!(^^)!
