### ISSUE TITLE
type: uploadVideoFinishが通知URLに届かない

### ISSUE THREAD

**Issue by supercattext** [mnakada/atomcam_tools#97]
ATOMCam Hack Ver.2.3.2 / ATOM_CAKP1JZIP Ver4.37.1.142を利用させて頂いております。ありがとうございます。
イベント通知のWebHookで動体検知録画終了のトグルスイッチをONにしているのですが、type: uploadVideoFinishが通知URLに届かないように思いますが仕様の変更などがございましたでしょうか。
ATOMCam Hack Ver.2.1.3 では以下のようなメッセージが届いておりました。ご教示いただけますと幸いです。
---
payload: object
type: "uploadVideoFinish"
device: "cam01"
sdcardFile: "alarm_record/20240408/014722.mp4"
---

**Comment by mnakada** [comment]
問題確認しました。次回updateで対応入れます。

**Comment by supercattext** [comment]
確認コメントありがとうございます。
メンテナンス機能がとても便利で様々なVerを試すことができました。
framerateの新機能も楽しみです。

**Comment by mnakada** [comment]
Ver.2.4.0で対応しました。

**Comment by supercattext** [comment]
"uploadVideoFinish"を受信できました。ありがとうございます。
