### ISSUE TITLE
2.4.1からの「カメラ画像」の大きさについて

### ISSUE THREAD

**Issue by Hiii555** [mnakada/atomcam_tools#98]
2.3系と違ってクリックで大小切り替わったりではなくサイズ指定なしの大きさで見切れてしまう事があるので
「カメラ画像」か「メディア設定」などの中にWebUIでの表示画像サイズという項目を作って表示サイズを
設定できるような項目を作っていただきたいです。

**Comment by mnakada** [comment]
？？？
windowの横幅で調整できませんか？
Browserの中で縦横を調整したい用途がわからないです。
見ている環境を教えてください。

**Comment by Hiii555** [comment]
もしや？と思いchromeでも確認してみましたがブラウザを「最大化」で見るとスクロールバーが
カメラ画像に付きませんか？Firefoxとchromeでチェックしましたのですが、ブラウザを９０％など大きさを
変更すると赤外線ボタンだけが意図した感じで直下にいるのですが・・・あれ？私だけかなぁ。
こんな感じでブラウザ最大化でカメラ画像みると日付見えないスクロール必要となりませんか？
![atom_image](https://github.com/mnakada/atomcam_tools/assets/161435860/8e11cc34-994b-4b17-8918-182b144a0659)

**Comment by mnakada** [comment]
なるほど。ちょっと確認します。

**Comment by mnakada** [comment]
Ver.2.4.2で修正しました。

**Comment by Hiii555** [comment]
ありがとうございます。今更新してみました。更新時に思ったのですがUpdateなどのLock箇所が
Lock解除、オン操作、実行だった順番がLock解除＝オン操作になり実行となっています。
意図した変更でしたら大丈夫なのですが他と同じになってしまうのでちょっと気になりました。

**Comment by mnakada** [comment]
そこは変わってないです。
もともとLockを解除してUpdateボタンを押すと実行されるという動作です。
