### ISSUE TITLE
クルーズ設定の一部の項目が機能していない（使えない）

### ISSUE THREAD

**Issue by katsumiota** [mnakada/atomcam_tools#99]
mnakada様、こんにちは。いつもツールを使わせていただいています。ありがとうございます。

さて、この前気がついたのですが、クルーズ設定内の「速度」の変更が反応しないのと「検知」のチェックボックスがクリックしてもオンに出来ないことに気がつきました。ですのでクルーズ機能が使えない状態です。
素人なのでよく解らなくて、もしかしたら自分の環境だけなのかもしれませんが、恐れ入りますがご確認いただけますでしょうか？

![Screenshot 2024-05-05 at 16-48-52 ATOMCam Hack Setup_02](https://github.com/mnakada/atomcam_tools/assets/156327908/5de8533f-a1bb-4ae8-b0e5-6c3f2e5a5dc3)

**Comment by mnakada** [comment]
ご指摘ありがとうございます。
Ver.2.4.3で修正しました。

**Comment by katsumiota** [comment]
> ご指摘ありがとうございます。 Ver.2.4.3で修正しました。

こんばんは。早速先ほどVer.2.4.3にアップデートをして確認してみましたところ、きちんと変更できるようになっていることを確認できました。素早い対応ありがとうございました。

**Comment by Hiii555** [comment]
使っていなかった機能でしたが確認したところ2.4.2では全く出来なかったのが2.4.3では出来るようになっていました。
